// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent/v1/channel.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ============================================================================
// Channel 健康状态
// ============================================================================
type ChannelState int32

const (
	ChannelState_CHANNEL_STATE_UNKNOWN   ChannelState = 0
	ChannelState_CHANNEL_STATE_HEALTHY   ChannelState = 1
	ChannelState_CHANNEL_STATE_DEGRADED  ChannelState = 2
	ChannelState_CHANNEL_STATE_UNHEALTHY ChannelState = 3
)

// Enum value maps for ChannelState.
var (
	ChannelState_name = map[int32]string{
		0: "CHANNEL_STATE_UNKNOWN",
		1: "CHANNEL_STATE_HEALTHY",
		2: "CHANNEL_STATE_DEGRADED",
		3: "CHANNEL_STATE_UNHEALTHY",
	}
	ChannelState_value = map[string]int32{
		"CHANNEL_STATE_UNKNOWN":   0,
		"CHANNEL_STATE_HEALTHY":   1,
		"CHANNEL_STATE_DEGRADED":  2,
		"CHANNEL_STATE_UNHEALTHY": 3,
	}
)

func (x ChannelState) Enum() *ChannelState {
	p := new(ChannelState)
	*p = x
	return p
}

func (x ChannelState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_channel_proto_enumTypes[0].Descriptor()
}

func (ChannelState) Type() protoreflect.EnumType {
	return &file_agent_v1_channel_proto_enumTypes[0]
}

func (x ChannelState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelState.Descriptor instead.
func (ChannelState) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{0}
}

// ============================================================================
// 内核信息
// ============================================================================
type KernelType int32

const (
	KernelType_KERNEL_TYPE_UNSPECIFIED KernelType = 0
	KernelType_KERNEL_TYPE_XRAY        KernelType = 1
	KernelType_KERNEL_TYPE_SINGBOX     KernelType = 2
)

// Enum value maps for KernelType.
var (
	KernelType_name = map[int32]string{
		0: "KERNEL_TYPE_UNSPECIFIED",
		1: "KERNEL_TYPE_XRAY",
		2: "KERNEL_TYPE_SINGBOX",
	}
	KernelType_value = map[string]int32{
		"KERNEL_TYPE_UNSPECIFIED": 0,
		"KERNEL_TYPE_XRAY":        1,
		"KERNEL_TYPE_SINGBOX":     2,
	}
)

func (x KernelType) Enum() *KernelType {
	p := new(KernelType)
	*p = x
	return p
}

func (x KernelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KernelType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_channel_proto_enumTypes[1].Descriptor()
}

func (KernelType) Type() protoreflect.EnumType {
	return &file_agent_v1_channel_proto_enumTypes[1]
}

func (x KernelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KernelType.Descriptor instead.
func (KernelType) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{1}
}

type HeartbeatAction int32

const (
	HeartbeatAction_HEARTBEAT_ACTION_NONE                   HeartbeatAction = 0
	HeartbeatAction_HEARTBEAT_ACTION_RELOAD                 HeartbeatAction = 1 // 需要重新拉取配置
	HeartbeatAction_HEARTBEAT_ACTION_RESTART                HeartbeatAction = 2 // 需要重启内核
	HeartbeatAction_HEARTBEAT_ACTION_MAINTENANCE            HeartbeatAction = 3 // 进入维护模式(停止接受新连接)
	HeartbeatAction_HEARTBEAT_ACTION_UPGRADE                HeartbeatAction = 4 // 有新版本Agent可用
	HeartbeatAction_HEARTBEAT_ACTION_SYNC_EXTERNAL_RESOURCES HeartbeatAction = 5 // 同步外部资源(nginx vhost/证书等)
)

// Enum value maps for HeartbeatAction.
var (
	HeartbeatAction_name = map[int32]string{
		0: "HEARTBEAT_ACTION_NONE",
		1: "HEARTBEAT_ACTION_RELOAD",
		2: "HEARTBEAT_ACTION_RESTART",
		3: "HEARTBEAT_ACTION_MAINTENANCE",
		4: "HEARTBEAT_ACTION_UPGRADE",
		5: "HEARTBEAT_ACTION_SYNC_EXTERNAL_RESOURCES",
	}
	HeartbeatAction_value = map[string]int32{
		"HEARTBEAT_ACTION_NONE":                   0,
		"HEARTBEAT_ACTION_RELOAD":                 1,
		"HEARTBEAT_ACTION_RESTART":                2,
		"HEARTBEAT_ACTION_MAINTENANCE":            3,
		"HEARTBEAT_ACTION_UPGRADE":                4,
		"HEARTBEAT_ACTION_SYNC_EXTERNAL_RESOURCES": 5,
	}
)

func (x HeartbeatAction) Enum() *HeartbeatAction {
	p := new(HeartbeatAction)
	*p = x
	return p
}

func (x HeartbeatAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeartbeatAction) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_channel_proto_enumTypes[2].Descriptor()
}

func (HeartbeatAction) Type() protoreflect.EnumType {
	return &file_agent_v1_channel_proto_enumTypes[2]
}

func (x HeartbeatAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeartbeatAction.Descriptor instead.
func (HeartbeatAction) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{2}
}

type MaintenanceCommand_Action int32

const (
	MaintenanceCommand_ACTION_UNSPECIFIED MaintenanceCommand_Action = 0
	MaintenanceCommand_ACTION_DRAIN       MaintenanceCommand_Action = 1 // 优雅关闭:停止接受新连接，等待现有连接结束
	MaintenanceCommand_ACTION_RESUME      MaintenanceCommand_Action = 2 // 恢复服务
	MaintenanceCommand_ACTION_RESTART     MaintenanceCommand_Action = 3 // 立即重启内核
	MaintenanceCommand_ACTION_STOP        MaintenanceCommand_Action = 4 // 停止内核
)

// Enum value maps for MaintenanceCommand_Action.
var (
	MaintenanceCommand_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_DRAIN",
		2: "ACTION_RESUME",
		3: "ACTION_RESTART",
		4: "ACTION_STOP",
	}
	MaintenanceCommand_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_DRAIN":       1,
		"ACTION_RESUME":      2,
		"ACTION_RESTART":     3,
		"ACTION_STOP":        4,
	}
)

func (x MaintenanceCommand_Action) Enum() *MaintenanceCommand_Action {
	p := new(MaintenanceCommand_Action)
	*p = x
	return p
}

func (x MaintenanceCommand_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MaintenanceCommand_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_channel_proto_enumTypes[3].Descriptor()
}

func (MaintenanceCommand_Action) Type() protoreflect.EnumType {
	return &file_agent_v1_channel_proto_enumTypes[3]
}

func (x MaintenanceCommand_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MaintenanceCommand_Action.Descriptor instead.
func (MaintenanceCommand_Action) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{17, 0}
}

type ChannelHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         ChannelState           `protobuf:"varint,1,opt,name=state,proto3,enum=agent.v1.ChannelState" json:"state,omitempty"`
	RttMs         int64                  `protobuf:"varint,2,opt,name=rtt_ms,json=rttMs,proto3" json:"rtt_ms,omitempty"`            // 当前通道RTT(毫秒)
	LastError     string                 `protobuf:"bytes,3,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"` // 最近错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelHealth) Reset() {
	*x = ChannelHealth{}
	mi := &file_agent_v1_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelHealth) ProtoMessage() {}

func (x *ChannelHealth) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelHealth.ProtoReflect.Descriptor instead.
func (*ChannelHealth) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{0}
}

func (x *ChannelHealth) GetState() ChannelState {
	if x != nil {
		return x.State
	}
	return ChannelState_CHANNEL_STATE_UNKNOWN
}

func (x *ChannelHealth) GetRttMs() int64 {
	if x != nil {
		return x.RttMs
	}
	return 0
}

func (x *ChannelHealth) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// ============================================================================
// 服务器负载指标 (Agent心跳上报)
// ============================================================================
type ServerLoad struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent     float32                `protobuf:"fixed32,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent     float32                `protobuf:"fixed32,2,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	MemTotalMb     int64                  `protobuf:"varint,3,opt,name=mem_total_mb,json=memTotalMb,proto3" json:"mem_total_mb,omitempty"`
	MemUsedMb      int64                  `protobuf:"varint,4,opt,name=mem_used_mb,json=memUsedMb,proto3" json:"mem_used_mb,omitempty"`
	DiskPercent    float32                `protobuf:"fixed32,5,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	DiskTotalGb    int64                  `protobuf:"varint,6,opt,name=disk_total_gb,json=diskTotalGb,proto3" json:"disk_total_gb,omitempty"`
	DiskUsedGb     int64                  `protobuf:"varint,7,opt,name=disk_used_gb,json=diskUsedGb,proto3" json:"disk_used_gb,omitempty"`
	NetworkInKbps  float32                `protobuf:"fixed32,8,opt,name=network_in_kbps,json=networkInKbps,proto3" json:"network_in_kbps,omitempty"`
	NetworkOutKbps float32                `protobuf:"fixed32,9,opt,name=network_out_kbps,json=networkOutKbps,proto3" json:"network_out_kbps,omitempty"`
	Load_1         float32                `protobuf:"fixed32,10,opt,name=load_1,json=load1,proto3" json:"load_1,omitempty"`
	Load_5         float32                `protobuf:"fixed32,11,opt,name=load_5,json=load5,proto3" json:"load_5,omitempty"`
	Load_15        float32                `protobuf:"fixed32,12,opt,name=load_15,json=load15,proto3" json:"load_15,omitempty"`
	TcpConnections int64                  `protobuf:"varint,13,opt,name=tcp_connections,json=tcpConnections,proto3" json:"tcp_connections,omitempty"`
	ActiveStreams  int64                  `protobuf:"varint,14,opt,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	Goroutines     int64                  `protobuf:"varint,15,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,16,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerLoad) Reset() {
	*x = ServerLoad{}
	mi := &file_agent_v1_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLoad) ProtoMessage() {}

func (x *ServerLoad) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLoad.ProtoReflect.Descriptor instead.
func (*ServerLoad) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{1}
}

func (x *ServerLoad) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ServerLoad) GetMemPercent() float32 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *ServerLoad) GetMemTotalMb() int64 {
	if x != nil {
		return x.MemTotalMb
	}
	return 0
}

func (x *ServerLoad) GetMemUsedMb() int64 {
	if x != nil {
		return x.MemUsedMb
	}
	return 0
}

func (x *ServerLoad) GetDiskPercent() float32 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *ServerLoad) GetDiskTotalGb() int64 {
	if x != nil {
		return x.DiskTotalGb
	}
	return 0
}

func (x *ServerLoad) GetDiskUsedGb() int64 {
	if x != nil {
		return x.DiskUsedGb
	}
	return 0
}

func (x *ServerLoad) GetNetworkInKbps() float32 {
	if x != nil {
		return x.NetworkInKbps
	}
	return 0
}

func (x *ServerLoad) GetNetworkOutKbps() float32 {
	if x != nil {
		return x.NetworkOutKbps
	}
	return 0
}

func (x *ServerLoad) GetLoad_1() float32 {
	if x != nil {
		return x.Load_1
	}
	return 0
}

func (x *ServerLoad) GetLoad_5() float32 {
	if x != nil {
		return x.Load_5
	}
	return 0
}

func (x *ServerLoad) GetLoad_15() float32 {
	if x != nil {
		return x.Load_15
	}
	return 0
}

func (x *ServerLoad) GetTcpConnections() int64 {
	if x != nil {
		return x.TcpConnections
	}
	return 0
}

func (x *ServerLoad) GetActiveStreams() int64 {
	if x != nil {
		return x.ActiveStreams
	}
	return 0
}

func (x *ServerLoad) GetGoroutines() int64 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *ServerLoad) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type KernelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          KernelType             `protobuf:"varint,1,opt,name=type,proto3,enum=agent.v1.KernelType" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ConfigVersion string                 `protobuf:"bytes,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"` // 当前生效的配置版本号
	Running       bool                   `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KernelInfo) Reset() {
	*x = KernelInfo{}
	mi := &file_agent_v1_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KernelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KernelInfo) ProtoMessage() {}

func (x *KernelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KernelInfo.ProtoReflect.Descriptor instead.
func (*KernelInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{2}
}

func (x *KernelInfo) GetType() KernelType {
	if x != nil {
		return x.Type
	}
	return KernelType_KERNEL_TYPE_UNSPECIFIED
}

func (x *KernelInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *KernelInfo) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *KernelInfo) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

// ============================================================================
// 节点在线状态 (心跳中上报每个节点的状态)
// ============================================================================
type NodeStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // UUID
	Enabled         bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	OnlineUsers     int64                  `protobuf:"varint,3,opt,name=online_users,json=onlineUsers,proto3" json:"online_users,omitempty"`
	TrafficInBytes  int64                  `protobuf:"varint,4,opt,name=traffic_in_bytes,json=trafficInBytes,proto3" json:"traffic_in_bytes,omitempty"` // 自上次上报累计
	TrafficOutBytes int64                  `protobuf:"varint,5,opt,name=traffic_out_bytes,json=trafficOutBytes,proto3" json:"traffic_out_bytes,omitempty"`
	ListenPort      int32                  `protobuf:"varint,6,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	LastError       string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_agent_v1_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{3}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NodeStatus) GetOnlineUsers() int64 {
	if x != nil {
		return x.OnlineUsers
	}
	return 0
}

func (x *NodeStatus) GetTrafficInBytes() int64 {
	if x != nil {
		return x.TrafficInBytes
	}
	return 0
}

func (x *NodeStatus) GetTrafficOutBytes() int64 {
	if x != nil {
		return x.TrafficOutBytes
	}
	return 0
}

func (x *NodeStatus) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *NodeStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

// ============================================================================
// 用户流量条目
// ============================================================================
type UserTraffic struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户UUID
	UploadBytes       int64                  `protobuf:"varint,2,opt,name=upload_bytes,json=uploadBytes,proto3" json:"upload_bytes,omitempty"`
	DownloadBytes     int64                  `protobuf:"varint,3,opt,name=download_bytes,json=downloadBytes,proto3" json:"download_bytes,omitempty"`
	ActiveConnections int64                  `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserTraffic) Reset() {
	*x = UserTraffic{}
	mi := &file_agent_v1_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTraffic) ProtoMessage() {}

func (x *UserTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTraffic.ProtoReflect.Descriptor instead.
func (*UserTraffic) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{4}
}

func (x *UserTraffic) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserTraffic) GetUploadBytes() int64 {
	if x != nil {
		return x.UploadBytes
	}
	return 0
}

func (x *UserTraffic) GetDownloadBytes() int64 {
	if x != nil {
		return x.DownloadBytes
	}
	return 0
}

func (x *UserTraffic) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

// ============================================================================
// 认证请求 (Agent 发送的第一条消息)
// ============================================================================
type AuthRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MachineToken    string                 `protobuf:"bytes,1,opt,name=machine_token,json=machineToken,proto3" json:"machine_token,omitempty"`                                    // 长效机器令牌(HMAC-SHA256生成)
	MachineId       string                 `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`                                             // 服务器code (如 "sg01")
	Nonce           string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`                                                                      // 随机字符串，每次连接唯一
	Timestamp       int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                             // Unix秒级时间戳
	Signature       string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`                                                              // HMAC-SHA256(machine_id+nonce+timestamp, machine_token)
	PreferredKernel KernelType             `protobuf:"varint,6,opt,name=preferred_kernel,json=preferredKernel,proto3,enum=agent.v1.KernelType" json:"preferred_kernel,omitempty"` // Agent偏好的内核类型
	AgentVersion    string                 `protobuf:"bytes,7,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`                                    // Agent版本号
	Hostname        string                 `protobuf:"bytes,8,opt,name=hostname,proto3" json:"hostname,omitempty"`                                                                // 主机名
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_agent_v1_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{5}
}

func (x *AuthRequest) GetMachineToken() string {
	if x != nil {
		return x.MachineToken
	}
	return ""
}

func (x *AuthRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *AuthRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *AuthRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AuthRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *AuthRequest) GetPreferredKernel() KernelType {
	if x != nil {
		return x.PreferredKernel
	}
	return KernelType_KERNEL_TYPE_UNSPECIFIED
}

func (x *AuthRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AuthRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type AuthAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ok               bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	SessionToken     string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`                // 会话Token (用于后续HMAC签名，不直接传输密钥)
	SessionExpiresAt int64                  `protobuf:"varint,3,opt,name=session_expires_at,json=sessionExpiresAt,proto3" json:"session_expires_at,omitempty"` // 会话过期时间(Unix秒)
	ServerId         string                 `protobuf:"bytes,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`                            // 分配的服务器UUID
	Error            string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                                                  // 失败原因
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthAck) Reset() {
	*x = AuthAck{}
	mi := &file_agent_v1_channel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAck) ProtoMessage() {}

func (x *AuthAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthAck.ProtoReflect.Descriptor instead.
func (*AuthAck) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{6}
}

func (x *AuthAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthAck) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *AuthAck) GetSessionExpiresAt() int64 {
	if x != nil {
		return x.SessionExpiresAt
	}
	return 0
}

func (x *AuthAck) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AuthAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ============================================================================
// 心跳
// ============================================================================
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion int64                  `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"` // Agent当前配置版本
	Load          *ServerLoad            `protobuf:"bytes,2,opt,name=load,proto3" json:"load,omitempty"`
	Kernel        *KernelInfo            `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Nodes         []*NodeStatus          `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Channel       *ChannelHealth         `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	PublicIp      string                 `protobuf:"bytes,6,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"` // Agent自检测到的公网IP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_v1_channel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *Heartbeat) GetLoad() *ServerLoad {
	if x != nil {
		return x.Load
	}
	return nil
}

func (x *Heartbeat) GetKernel() *KernelInfo {
	if x != nil {
		return x.Kernel
	}
	return nil
}

func (x *Heartbeat) GetNodes() []*NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Heartbeat) GetChannel() *ChannelHealth {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *Heartbeat) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

type HeartbeatAck struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Action              HeartbeatAction        `protobuf:"varint,1,opt,name=action,proto3,enum=agent.v1.HeartbeatAction" json:"action,omitempty"`
	LatestConfigVersion int64                  `protobuf:"varint,2,opt,name=latest_config_version,json=latestConfigVersion,proto3" json:"latest_config_version,omitempty"` // 面板最新配置版本号
	ServerTime          int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`                              // 面板当前时间(用于时钟同步)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_agent_v1_channel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatAck) GetAction() HeartbeatAction {
	if x != nil {
		return x.Action
	}
	return HeartbeatAction_HEARTBEAT_ACTION_NONE
}

func (x *HeartbeatAck) GetLatestConfigVersion() int64 {
	if x != nil {
		return x.LatestConfigVersion
	}
	return 0
}

func (x *HeartbeatAck) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// ============================================================================
// 配置下发
// ============================================================================
type NodeSpec struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	NodeId     string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Code       string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name       string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Protocol   string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`                        // vless/trojan/vmess/shadowsocks/hysteria2/tuic/anytls
	Address    string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`                          // 显示给用户的地址
	PublicPort int32                  `protobuf:"varint,6,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"` // 连接端口(用户连接的端口)
	ListenPort int32                  `protobuf:"varint,7,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"` // 监听端口(实际监听端口)
	Enabled    bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AllowUdp   bool                   `protobuf:"varint,9,opt,name=allow_udp,json=allowUdp,proto3" json:"allow_udp,omitempty"`
	// 传输层
	TransportType     string `protobuf:"bytes,10,opt,name=transport_type,json=transportType,proto3" json:"transport_type,omitempty"`             // tcp/ws/grpc/http2/quic/kcp/httpupgrade
	TransportSettings []byte `protobuf:"bytes,11,opt,name=transport_settings,json=transportSettings,proto3" json:"transport_settings,omitempty"` // 传输层配置JSON
	Path              string `protobuf:"bytes,12,opt,name=path,proto3" json:"path,omitempty"`                                                    // ws/grpc路径
	HostHeader        string `protobuf:"bytes,13,opt,name=host_header,json=hostHeader,proto3" json:"host_header,omitempty"`                      // HTTP Host
	// 安全层
	SecurityType     string   `protobuf:"bytes,14,opt,name=security_type,json=securityType,proto3" json:"security_type,omitempty"` // none/tls/reality
	Sni              string   `protobuf:"bytes,15,opt,name=sni,proto3" json:"sni,omitempty"`
	Alpn             []string `protobuf:"bytes,16,rep,name=alpn,proto3" json:"alpn,omitempty"`
	Fingerprint      string   `protobuf:"bytes,17,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`                                   // uTLS指纹
	SecuritySettings []byte   `protobuf:"bytes,18,opt,name=security_settings,json=securitySettings,proto3" json:"security_settings,omitempty"` // TLS/Reality 详细配置JSON
	// 协议凭证
	Credentials []byte `protobuf:"bytes,19,opt,name=credentials,proto3" json:"credentials,omitempty"` // 凭证JSON (uuid/password/keypair等)
	// 流量控制
	SpeedLimitMbps int32   `protobuf:"varint,20,opt,name=speed_limit_mbps,json=speedLimitMbps,proto3" json:"speed_limit_mbps,omitempty"`
	DeviceLimit    int32   `protobuf:"varint,21,opt,name=device_limit,json=deviceLimit,proto3" json:"device_limit,omitempty"`
	TrafficRate    float64 `protobuf:"fixed64,22,opt,name=traffic_rate,json=trafficRate,proto3" json:"traffic_rate,omitempty"`
	Flow           string  `protobuf:"bytes,23,opt,name=flow,proto3" json:"flow,omitempty"` // xtls-rprx-vision等
	// 路由
	Tags            []string `protobuf:"bytes,24,rep,name=tags,proto3" json:"tags,omitempty"`
	RouteGroup      string   `protobuf:"bytes,25,opt,name=route_group,json=routeGroup,proto3" json:"route_group,omitempty"`
	CustomOutbounds []byte   `protobuf:"bytes,26,opt,name=custom_outbounds,json=customOutbounds,proto3" json:"custom_outbounds,omitempty"` // 自定义Outbounds JSON
	CustomRoutes    []byte   `protobuf:"bytes,27,opt,name=custom_routes,json=customRoutes,proto3" json:"custom_routes,omitempty"`          // 自定义Routes JSON
	// 父节点(链式代理)
	ParentNodeId  string `protobuf:"bytes,28,opt,name=parent_node_id,json=parentNodeId,proto3" json:"parent_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSpec) Reset() {
	*x = NodeSpec{}
	mi := &file_agent_v1_channel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSpec) ProtoMessage() {}

func (x *NodeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSpec.ProtoReflect.Descriptor instead.
func (*NodeSpec) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{9}
}

func (x *NodeSpec) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeSpec) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *NodeSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeSpec) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NodeSpec) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeSpec) GetPublicPort() int32 {
	if x != nil {
		return x.PublicPort
	}
	return 0
}

func (x *NodeSpec) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *NodeSpec) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NodeSpec) GetAllowUdp() bool {
	if x != nil {
		return x.AllowUdp
	}
	return false
}

func (x *NodeSpec) GetTransportType() string {
	if x != nil {
		return x.TransportType
	}
	return ""
}

func (x *NodeSpec) GetTransportSettings() []byte {
	if x != nil {
		return x.TransportSettings
	}
	return nil
}

func (x *NodeSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NodeSpec) GetHostHeader() string {
	if x != nil {
		return x.HostHeader
	}
	return ""
}

func (x *NodeSpec) GetSecurityType() string {
	if x != nil {
		return x.SecurityType
	}
	return ""
}

func (x *NodeSpec) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *NodeSpec) GetAlpn() []string {
	if x != nil {
		return x.Alpn
	}
	return nil
}

func (x *NodeSpec) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *NodeSpec) GetSecuritySettings() []byte {
	if x != nil {
		return x.SecuritySettings
	}
	return nil
}

func (x *NodeSpec) GetCredentials() []byte {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *NodeSpec) GetSpeedLimitMbps() int32 {
	if x != nil {
		return x.SpeedLimitMbps
	}
	return 0
}

func (x *NodeSpec) GetDeviceLimit() int32 {
	if x != nil {
		return x.DeviceLimit
	}
	return 0
}

func (x *NodeSpec) GetTrafficRate() float64 {
	if x != nil {
		return x.TrafficRate
	}
	return 0
}

func (x *NodeSpec) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *NodeSpec) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *NodeSpec) GetRouteGroup() string {
	if x != nil {
		return x.RouteGroup
	}
	return ""
}

func (x *NodeSpec) GetCustomOutbounds() []byte {
	if x != nil {
		return x.CustomOutbounds
	}
	return nil
}

func (x *NodeSpec) GetCustomRoutes() []byte {
	if x != nil {
		return x.CustomRoutes
	}
	return nil
}

func (x *NodeSpec) GetParentNodeId() string {
	if x != nil {
		return x.ParentNodeId
	}
	return ""
}

type ConfigPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ConfigHash    string                 `protobuf:"bytes,2,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"` // SHA256(所有NodeSpec的规范序列化)
	Nodes         []*NodeSpec            `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	GlobalConfig  []byte                 `protobuf:"bytes,4,opt,name=global_config,json=globalConfig,proto3" json:"global_config,omitempty"` // 全局配置 (DNS/Log/API等)
	FullReplace   bool                   `protobuf:"varint,5,opt,name=full_replace,json=fullReplace,proto3" json:"full_replace,omitempty"`   // true=全量替换; false=增量更新
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigPush) Reset() {
	*x = ConfigPush{}
	mi := &file_agent_v1_channel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigPush) ProtoMessage() {}

func (x *ConfigPush) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigPush.ProtoReflect.Descriptor instead.
func (*ConfigPush) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigPush) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigPush) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ConfigPush) GetNodes() []*NodeSpec {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ConfigPush) GetGlobalConfig() []byte {
	if x != nil {
		return x.GlobalConfig
	}
	return nil
}

func (x *ConfigPush) GetFullReplace() bool {
	if x != nil {
		return x.FullReplace
	}
	return false
}

// ConfigResult 是 Agent 应用配置后上报结果
type ConfigResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ConfigHash      string                 `protobuf:"bytes,2,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	Success         bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ApplyDurationMs int64                  `protobuf:"varint,5,opt,name=apply_duration_ms,json=applyDurationMs,proto3" json:"apply_duration_ms,omitempty"` // 配置应用耗时
	KernelType      string                 `protobuf:"bytes,6,opt,name=kernel_type,json=kernelType,proto3" json:"kernel_type,omitempty"`                   // 应用配置的内核类型
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfigResult) Reset() {
	*x = ConfigResult{}
	mi := &file_agent_v1_channel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResult) ProtoMessage() {}

func (x *ConfigResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResult.ProtoReflect.Descriptor instead.
func (*ConfigResult) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigResult) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigResult) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *ConfigResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ConfigResult) GetApplyDurationMs() int64 {
	if x != nil {
		return x.ApplyDurationMs
	}
	return 0
}

func (x *ConfigResult) GetKernelType() string {
	if x != nil {
		return x.KernelType
	}
	return ""
}

// ============================================================================
// 流量上报
// ============================================================================
type TrafficReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Seq              int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"` // 单调递增序列号
	Timestamp        int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Entries          []*UserTraffic         `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	TotalOnlineUsers int64                  `protobuf:"varint,4,opt,name=total_online_users,json=totalOnlineUsers,proto3" json:"total_online_users,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrafficReport) Reset() {
	*x = TrafficReport{}
	mi := &file_agent_v1_channel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficReport) ProtoMessage() {}

func (x *TrafficReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficReport.ProtoReflect.Descriptor instead.
func (*TrafficReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{12}
}

func (x *TrafficReport) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TrafficReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TrafficReport) GetEntries() []*UserTraffic {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *TrafficReport) GetTotalOnlineUsers() int64 {
	if x != nil {
		return x.TotalOnlineUsers
	}
	return 0
}

// ============================================================================
// 用户封禁通知
// ============================================================================
type UserBanNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBanNotice) Reset() {
	*x = UserBanNotice{}
	mi := &file_agent_v1_channel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBanNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBanNotice) ProtoMessage() {}

func (x *UserBanNotice) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBanNotice.ProtoReflect.Descriptor instead.
func (*UserBanNotice) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{13}
}

func (x *UserBanNotice) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *UserBanNotice) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UserBanNotice) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// ============================================================================
// 证书续签通知
// ============================================================================
type CertRenewNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CertType      string                 `protobuf:"bytes,2,opt,name=cert_type,json=certType,proto3" json:"cert_type,omitempty"` // tls/ech
	CertPath      string                 `protobuf:"bytes,3,opt,name=cert_path,json=certPath,proto3" json:"cert_path,omitempty"`
	KeyPath       string                 `protobuf:"bytes,4,opt,name=key_path,json=keyPath,proto3" json:"key_path,omitempty"`
	CertData      []byte                 `protobuf:"bytes,5,opt,name=cert_data,json=certData,proto3" json:"cert_data,omitempty"` // 证书数据(PEM格式)
	KeyData       []byte                 `protobuf:"bytes,6,opt,name=key_data,json=keyData,proto3" json:"key_data,omitempty"`    // 密钥数据(PEM格式)
	ExpiresAt     int64                  `protobuf:"varint,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertRenewNotice) Reset() {
	*x = CertRenewNotice{}
	mi := &file_agent_v1_channel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRenewNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRenewNotice) ProtoMessage() {}

func (x *CertRenewNotice) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRenewNotice.ProtoReflect.Descriptor instead.
func (*CertRenewNotice) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{14}
}

func (x *CertRenewNotice) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CertRenewNotice) GetCertType() string {
	if x != nil {
		return x.CertType
	}
	return ""
}

func (x *CertRenewNotice) GetCertPath() string {
	if x != nil {
		return x.CertPath
	}
	return ""
}

func (x *CertRenewNotice) GetKeyPath() string {
	if x != nil {
		return x.KeyPath
	}
	return ""
}

func (x *CertRenewNotice) GetCertData() []byte {
	if x != nil {
		return x.CertData
	}
	return nil
}

func (x *CertRenewNotice) GetKeyData() []byte {
	if x != nil {
		return x.KeyData
	}
	return nil
}

func (x *CertRenewNotice) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// ============================================================================
// Ping/Pong (通道健康检测)
// ============================================================================
type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // 可选随机数据用于RTT测量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_agent_v1_channel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{15}
}

func (x *Ping) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Ping) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PingTimestamp int64                  `protobuf:"varint,2,opt,name=ping_timestamp,json=pingTimestamp,proto3" json:"ping_timestamp,omitempty"` // 对应Ping的timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_agent_v1_channel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{16}
}

func (x *Pong) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Pong) GetPingTimestamp() int64 {
	if x != nil {
		return x.PingTimestamp
	}
	return 0
}

// ============================================================================
// 维护模式指令
// ============================================================================
type MaintenanceCommand struct {
	state               protoimpl.MessageState    `protogen:"open.v1"`
	Action              MaintenanceCommand_Action `protobuf:"varint,1,opt,name=action,proto3,enum=agent.v1.MaintenanceCommand_Action" json:"action,omitempty"`
	Reason              string                    `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	DrainTimeoutSeconds int64                     `protobuf:"varint,3,opt,name=drain_timeout_seconds,json=drainTimeoutSeconds,proto3" json:"drain_timeout_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MaintenanceCommand) Reset() {
	*x = MaintenanceCommand{}
	mi := &file_agent_v1_channel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceCommand) ProtoMessage() {}

func (x *MaintenanceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceCommand.ProtoReflect.Descriptor instead.
func (*MaintenanceCommand) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{17}
}

func (x *MaintenanceCommand) GetAction() MaintenanceCommand_Action {
	if x != nil {
		return x.Action
	}
	return MaintenanceCommand_ACTION_UNSPECIFIED
}

func (x *MaintenanceCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MaintenanceCommand) GetDrainTimeoutSeconds() int64 {
	if x != nil {
		return x.DrainTimeoutSeconds
	}
	return 0
}

// ============================================================================
// Delta Sync 增量同步（P2 支柱：替代全量 Manifest 下发）
// 面板在用户增删/套餐变更时推送轻量 Delta，Agent 零断流热更
// ============================================================================
type DeltaUserChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	InboundTag    string                 `protobuf:"bytes,3,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`                                                                     // Hy2/TUIC 密码
	Extra         map[string]string      `protobuf:"bytes,6,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 协议专有字段(flow/method等)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaUserChange) Reset() {
	*x = DeltaUserChange{}
	mi := &file_agent_v1_channel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaUserChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaUserChange) ProtoMessage() {}

func (x *DeltaUserChange) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaUserChange.ProtoReflect.Descriptor instead.
func (*DeltaUserChange) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{18}
}

func (x *DeltaUserChange) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DeltaUserChange) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DeltaUserChange) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *DeltaUserChange) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *DeltaUserChange) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DeltaUserChange) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type DeltaSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                       // 目标节点ID(UUID)
	ServerCode    string                 `protobuf:"bytes,2,opt,name=server_code,json=serverCode,proto3" json:"server_code,omitempty"`           // 目标服务器code
	Kernel        KernelType             `protobuf:"varint,3,opt,name=kernel,proto3,enum=agent.v1.KernelType" json:"kernel,omitempty"`           // 目标内核(xray/sing-box)
	AddUsers      []*DeltaUserChange     `protobuf:"bytes,4,rep,name=add_users,json=addUsers,proto3" json:"add_users,omitempty"`                 // 新增/修改的用户
	DelUsers      []string               `protobuf:"bytes,5,rep,name=del_users,json=delUsers,proto3" json:"del_users,omitempty"`                 // 待删除用户email
	ConfigVersion int64                  `protobuf:"varint,6,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"` // 目标配置版本号
	ConfigHash    string                 `protobuf:"bytes,7,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`           // 预期配置hash(一致性校验)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaSync) Reset() {
	*x = DeltaSync{}
	mi := &file_agent_v1_channel_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaSync) ProtoMessage() {}

func (x *DeltaSync) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaSync.ProtoReflect.Descriptor instead.
func (*DeltaSync) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{19}
}

func (x *DeltaSync) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DeltaSync) GetServerCode() string {
	if x != nil {
		return x.ServerCode
	}
	return ""
}

func (x *DeltaSync) GetKernel() KernelType {
	if x != nil {
		return x.Kernel
	}
	return KernelType_KERNEL_TYPE_UNSPECIFIED
}

func (x *DeltaSync) GetAddUsers() []*DeltaUserChange {
	if x != nil {
		return x.AddUsers
	}
	return nil
}

func (x *DeltaSync) GetDelUsers() []string {
	if x != nil {
		return x.DelUsers
	}
	return nil
}

func (x *DeltaSync) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *DeltaSync) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

type DeltaAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion   int64                  `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ApplyDurationMs int64                  `protobuf:"varint,4,opt,name=apply_duration_ms,json=applyDurationMs,proto3" json:"apply_duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeltaAck) Reset() {
	*x = DeltaAck{}
	mi := &file_agent_v1_channel_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaAck) ProtoMessage() {}

func (x *DeltaAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaAck.ProtoReflect.Descriptor instead.
func (*DeltaAck) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{20}
}

func (x *DeltaAck) GetConfigVersion() int64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *DeltaAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeltaAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeltaAck) GetApplyDurationMs() int64 {
	if x != nil {
		return x.ApplyDurationMs
	}
	return 0
}

// ============================================================================
// 日志流（Agent→Panel，用于AI诊断采集内核日志）
// ============================================================================
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                    // 日志时间Unix毫秒
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`                                                                           // xray/sing-box/agent/warp
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`                                                                             // info/warn/error/debug
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                                                                         // 日志内容
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 附加标签(node_id/connection_id等)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_agent_v1_channel_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{21}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	MachineId     string                 `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"` // 冗余字段，服务端也可从stream auth获取
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_agent_v1_channel_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{22}
}

func (x *LogChunk) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LogChunk) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

// ============================================================================
// Agent 发送的消息信封
// ============================================================================
type AgentMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Seq       int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`             // 单调递增，从1开始
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 发送时间Unix毫秒
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Auth
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_ConfigResult
	//	*AgentMessage_TrafficReport
	//	*AgentMessage_Ping
	//	*AgentMessage_LogChunk
	//	*AgentMessage_DeltaAck
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_v1_channel_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{23}
}

func (x *AgentMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AgentMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetAuth() *AuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetConfigResult() *ConfigResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ConfigResult); ok {
			return x.ConfigResult
		}
	}
	return nil
}

func (x *AgentMessage) GetTrafficReport() *TrafficReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TrafficReport); ok {
			return x.TrafficReport
		}
	}
	return nil
}

func (x *AgentMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *AgentMessage) GetLogChunk() *LogChunk {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_LogChunk); ok {
			return x.LogChunk
		}
	}
	return nil
}

func (x *AgentMessage) GetDeltaAck() *DeltaAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_DeltaAck); ok {
			return x.DeltaAck
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Auth struct {
	Auth *AuthRequest `protobuf:"bytes,3,opt,name=auth,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_ConfigResult struct {
	ConfigResult *ConfigResult `protobuf:"bytes,5,opt,name=config_result,json=configResult,proto3,oneof"`
}

type AgentMessage_TrafficReport struct {
	TrafficReport *TrafficReport `protobuf:"bytes,6,opt,name=traffic_report,json=trafficReport,proto3,oneof"`
}

type AgentMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,7,opt,name=ping,proto3,oneof"`
}

type AgentMessage_LogChunk struct {
	LogChunk *LogChunk `protobuf:"bytes,8,opt,name=log_chunk,json=logChunk,proto3,oneof"` // 日志块（批量发送，减少帧数量）
}

type AgentMessage_DeltaAck struct {
	DeltaAck *DeltaAck `protobuf:"bytes,9,opt,name=delta_ack,json=deltaAck,proto3,oneof"` // Delta Sync 确认
}

func (*AgentMessage_Auth) isAgentMessage_Payload() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Payload() {}

func (*AgentMessage_ConfigResult) isAgentMessage_Payload() {}

func (*AgentMessage_TrafficReport) isAgentMessage_Payload() {}

func (*AgentMessage_Ping) isAgentMessage_Payload() {}

func (*AgentMessage_LogChunk) isAgentMessage_Payload() {}

func (*AgentMessage_DeltaAck) isAgentMessage_Payload() {}

// ============================================================================
// Panel 发送的消息信封
// ============================================================================
type PanelMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Seq       int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PanelMessage_AuthAck
	//	*PanelMessage_HeartbeatAck
	//	*PanelMessage_ConfigPush
	//	*PanelMessage_UserBan
	//	*PanelMessage_CertRenew
	//	*PanelMessage_Pong
	//	*PanelMessage_Maintenance
	//	*PanelMessage_DeltaSync
	Payload       isPanelMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelMessage) Reset() {
	*x = PanelMessage{}
	mi := &file_agent_v1_channel_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelMessage) ProtoMessage() {}

func (x *PanelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_channel_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelMessage.ProtoReflect.Descriptor instead.
func (*PanelMessage) Descriptor() ([]byte, []int) {
	return file_agent_v1_channel_proto_rawDescGZIP(), []int{24}
}

func (x *PanelMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PanelMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PanelMessage) GetPayload() isPanelMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PanelMessage) GetAuthAck() *AuthAck {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_AuthAck); ok {
			return x.AuthAck
		}
	}
	return nil
}

func (x *PanelMessage) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *PanelMessage) GetConfigPush() *ConfigPush {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_ConfigPush); ok {
			return x.ConfigPush
		}
	}
	return nil
}

func (x *PanelMessage) GetUserBan() *UserBanNotice {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_UserBan); ok {
			return x.UserBan
		}
	}
	return nil
}

func (x *PanelMessage) GetCertRenew() *CertRenewNotice {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_CertRenew); ok {
			return x.CertRenew
		}
	}
	return nil
}

func (x *PanelMessage) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *PanelMessage) GetMaintenance() *MaintenanceCommand {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_Maintenance); ok {
			return x.Maintenance
		}
	}
	return nil
}

func (x *PanelMessage) GetDeltaSync() *DeltaSync {
	if x != nil {
		if x, ok := x.Payload.(*PanelMessage_DeltaSync); ok {
			return x.DeltaSync
		}
	}
	return nil
}

type isPanelMessage_Payload interface {
	isPanelMessage_Payload()
}

type PanelMessage_AuthAck struct {
	AuthAck *AuthAck `protobuf:"bytes,3,opt,name=auth_ack,json=authAck,proto3,oneof"`
}

type PanelMessage_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,4,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type PanelMessage_ConfigPush struct {
	ConfigPush *ConfigPush `protobuf:"bytes,5,opt,name=config_push,json=configPush,proto3,oneof"`
}

type PanelMessage_UserBan struct {
	UserBan *UserBanNotice `protobuf:"bytes,6,opt,name=user_ban,json=userBan,proto3,oneof"`
}

type PanelMessage_CertRenew struct {
	CertRenew *CertRenewNotice `protobuf:"bytes,7,opt,name=cert_renew,json=certRenew,proto3,oneof"`
}

type PanelMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,8,opt,name=pong,proto3,oneof"`
}

type PanelMessage_Maintenance struct {
	Maintenance *MaintenanceCommand `protobuf:"bytes,9,opt,name=maintenance,proto3,oneof"`
}

type PanelMessage_DeltaSync struct {
	DeltaSync *DeltaSync `protobuf:"bytes,10,opt,name=delta_sync,json=deltaSync,proto3,oneof"` // Delta Sync 增量用户变更
}

func (*PanelMessage_AuthAck) isPanelMessage_Payload() {}

func (*PanelMessage_HeartbeatAck) isPanelMessage_Payload() {}

func (*PanelMessage_ConfigPush) isPanelMessage_Payload() {}

func (*PanelMessage_UserBan) isPanelMessage_Payload() {}

func (*PanelMessage_CertRenew) isPanelMessage_Payload() {}

func (*PanelMessage_Pong) isPanelMessage_Payload() {}

func (*PanelMessage_Maintenance) isPanelMessage_Payload() {}

func (*PanelMessage_DeltaSync) isPanelMessage_Payload() {}

var File_agent_v1_channel_proto protoreflect.FileDescriptor

const file_agent_v1_channel_proto_rawDesc = "" +
	"\n" +
	"\x16agent/v1/channel.proto\x12\bagent.v1\"s\n" +
	"\rChannelHealth\x12,\n" +
	"\x05state\x18\x01 \x01(\x0e2\x16.agent.v1.ChannelStateR\x05state\x12\x15\n" +
	"\x06rtt_ms\x18\x02 \x01(\x03R\x05rttMs\x12\x1d\n" +
	"\n" +
	"last_error\x18\x03 \x01(\tR\tlastError\"\xa9\x04\n" +
	"\n" +
	"ServerLoad\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x02R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x02 \x01(\x02R\n" +
	"memPercent\x12 \n" +
	"\fmem_total_mb\x18\x03 \x01(\x03R\n" +
	"memTotalMb\x12\x1e\n" +
	"\vmem_used_mb\x18\x04 \x01(\x03R\tmemUsedMb\x12!\n" +
	"\fdisk_percent\x18\x05 \x01(\x02R\vdiskPercent\x12\"\n" +
	"\rdisk_total_gb\x18\x06 \x01(\x03R\vdiskTotalGb\x12 \n" +
	"\fdisk_used_gb\x18\a \x01(\x03R\n" +
	"diskUsedGb\x12&\n" +
	"\x0fnetwork_in_kbps\x18\b \x01(\x02R\rnetworkInKbps\x12(\n" +
	"\x10network_out_kbps\x18\t \x01(\x02R\x0enetworkOutKbps\x12\x15\n" +
	"\x06load_1\x18\n" +
	" \x01(\x02R\x05load1\x12\x15\n" +
	"\x06load_5\x18\v \x01(\x02R\x05load5\x12\x17\n" +
	"\aload_15\x18\f \x01(\x02R\x06load15\x12'\n" +
	"\x0ftcp_connections\x18\r \x01(\x03R\x0etcpConnections\x12%\n" +
	"\x0eactive_streams\x18\x0e \x01(\x03R\ractiveStreams\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x0f \x01(\x03R\n" +
	"goroutines\x12%\n" +
	"\x0euptime_seconds\x18\x10 \x01(\x03R\ruptimeSeconds\"\x91\x01\n" +
	"\n" +
	"KernelInfo\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.agent.v1.KernelTypeR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\tR\rconfigVersion\x12\x18\n" +
	"\arunning\x18\x04 \x01(\bR\arunning\"\xf8\x01\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12!\n" +
	"\fonline_users\x18\x03 \x01(\x03R\vonlineUsers\x12(\n" +
	"\x10traffic_in_bytes\x18\x04 \x01(\x03R\x0etrafficInBytes\x12*\n" +
	"\x11traffic_out_bytes\x18\x05 \x01(\x03R\x0ftrafficOutBytes\x12\x1f\n" +
	"\vlisten_port\x18\x06 \x01(\x05R\n" +
	"listenPort\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\"\x9f\x01\n" +
	"\vUserTraffic\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fupload_bytes\x18\x02 \x01(\x03R\vuploadBytes\x12%\n" +
	"\x0edownload_bytes\x18\x03 \x01(\x03R\rdownloadBytes\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\x03R\x11activeConnections\"\xa5\x02\n" +
	"\vAuthRequest\x12#\n" +
	"\rmachine_token\x18\x01 \x01(\tR\fmachineToken\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12?\n" +
	"\x10preferred_kernel\x18\x06 \x01(\x0e2\x14.agent.v1.KernelTypeR\x0fpreferredKernel\x12#\n" +
	"\ragent_version\x18\a \x01(\tR\fagentVersion\x12\x1a\n" +
	"\bhostname\x18\b \x01(\tR\bhostname\"\x9f\x01\n" +
	"\aAuthAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x12,\n" +
	"\x12session_expires_at\x18\x03 \x01(\x03R\x10sessionExpiresAt\x12\x1b\n" +
	"\tserver_id\x18\x04 \x01(\tR\bserverId\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x86\x02\n" +
	"\tHeartbeat\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x03R\rconfigVersion\x12(\n" +
	"\x04load\x18\x02 \x01(\v2\x14.agent.v1.ServerLoadR\x04load\x12,\n" +
	"\x06kernel\x18\x03 \x01(\v2\x14.agent.v1.KernelInfoR\x06kernel\x12*\n" +
	"\x05nodes\x18\x04 \x03(\v2\x14.agent.v1.NodeStatusR\x05nodes\x121\n" +
	"\achannel\x18\x05 \x01(\v2\x17.agent.v1.ChannelHealthR\achannel\x12\x1b\n" +
	"\tpublic_ip\x18\x06 \x01(\tR\bpublicIp\"\x96\x01\n" +
	"\fHeartbeatAck\x121\n" +
	"\x06action\x18\x01 \x01(\x0e2\x19.agent.v1.HeartbeatActionR\x06action\x122\n" +
	"\x15latest_config_version\x18\x02 \x01(\x03R\x13latestConfigVersion\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\"\xf0\x06\n" +
	"\bNodeSpec\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x1f\n" +
	"\vpublic_port\x18\x06 \x01(\x05R\n" +
	"publicPort\x12\x1f\n" +
	"\vlisten_port\x18\a \x01(\x05R\n" +
	"listenPort\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x12\x1b\n" +
	"\tallow_udp\x18\t \x01(\bR\ballowUdp\x12%\n" +
	"\x0etransport_type\x18\n" +
	" \x01(\tR\rtransportType\x12-\n" +
	"\x12transport_settings\x18\v \x01(\fR\x11transportSettings\x12\x12\n" +
	"\x04path\x18\f \x01(\tR\x04path\x12\x1f\n" +
	"\vhost_header\x18\r \x01(\tR\n" +
	"hostHeader\x12#\n" +
	"\rsecurity_type\x18\x0e \x01(\tR\fsecurityType\x12\x10\n" +
	"\x03sni\x18\x0f \x01(\tR\x03sni\x12\x12\n" +
	"\x04alpn\x18\x10 \x03(\tR\x04alpn\x12 \n" +
	"\vfingerprint\x18\x11 \x01(\tR\vfingerprint\x12+\n" +
	"\x11security_settings\x18\x12 \x01(\fR\x10securitySettings\x12 \n" +
	"\vcredentials\x18\x13 \x01(\fR\vcredentials\x12(\n" +
	"\x10speed_limit_mbps\x18\x14 \x01(\x05R\x0espeedLimitMbps\x12!\n" +
	"\fdevice_limit\x18\x15 \x01(\x05R\vdeviceLimit\x12!\n" +
	"\ftraffic_rate\x18\x16 \x01(\x01R\vtrafficRate\x12\x12\n" +
	"\x04flow\x18\x17 \x01(\tR\x04flow\x12\x12\n" +
	"\x04tags\x18\x18 \x03(\tR\x04tags\x12\x1f\n" +
	"\vroute_group\x18\x19 \x01(\tR\n" +
	"routeGroup\x12)\n" +
	"\x10custom_outbounds\x18\x1a \x01(\fR\x0fcustomOutbounds\x12#\n" +
	"\rcustom_routes\x18\x1b \x01(\fR\fcustomRoutes\x12$\n" +
	"\x0eparent_node_id\x18\x1c \x01(\tR\fparentNodeId\"\xb9\x01\n" +
	"\n" +
	"ConfigPush\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1f\n" +
	"\vconfig_hash\x18\x02 \x01(\tR\n" +
	"configHash\x12(\n" +
	"\x05nodes\x18\x03 \x03(\v2\x12.agent.v1.NodeSpecR\x05nodes\x12#\n" +
	"\rglobal_config\x18\x04 \x01(\fR\fglobalConfig\x12!\n" +
	"\ffull_replace\x18\x05 \x01(\bR\vfullReplace\"\xc6\x01\n" +
	"\fConfigResult\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x1f\n" +
	"\vconfig_hash\x18\x02 \x01(\tR\n" +
	"configHash\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12*\n" +
	"\x11apply_duration_ms\x18\x05 \x01(\x03R\x0fapplyDurationMs\x12\x1f\n" +
	"\vkernel_type\x18\x06 \x01(\tR\n" +
	"kernelType\"\x9e\x01\n" +
	"\rTrafficReport\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12/\n" +
	"\aentries\x18\x03 \x03(\v2\x15.agent.v1.UserTrafficR\aentries\x12,\n" +
	"\x12total_online_users\x18\x04 \x01(\x03R\x10totalOnlineUsers\"`\n" +
	"\rUserBanNotice\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xd6\x01\n" +
	"\x0fCertRenewNotice\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tcert_type\x18\x02 \x01(\tR\bcertType\x12\x1b\n" +
	"\tcert_path\x18\x03 \x01(\tR\bcertPath\x12\x19\n" +
	"\bkey_path\x18\x04 \x01(\tR\akeyPath\x12\x1b\n" +
	"\tcert_data\x18\x05 \x01(\fR\bcertData\x12\x19\n" +
	"\bkey_data\x18\x06 \x01(\fR\akeyData\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x03R\texpiresAt\">\n" +
	"\x04Ping\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"K\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0eping_timestamp\x18\x02 \x01(\x03R\rpingTimestamp\"\x89\x02\n" +
	"\x12MaintenanceCommand\x12;\n" +
	"\x06action\x18\x01 \x01(\x0e2#.agent.v1.MaintenanceCommand.ActionR\x06action\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x122\n" +
	"\x15drain_timeout_seconds\x18\x03 \x01(\x03R\x13drainTimeoutSeconds\"j\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fACTION_DRAIN\x10\x01\x12\x11\n" +
	"\rACTION_RESUME\x10\x02\x12\x12\n" +
	"\x0eACTION_RESTART\x10\x03\x12\x0f\n" +
	"\vACTION_STOP\x10\x04\"\x84\x02\n" +
	"\x0fDeltaUserChange\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vinbound_tag\x18\x03 \x01(\tR\n" +
	"inboundTag\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12:\n" +
	"\x05extra\x18\x06 \x03(\v2$.agent.v1.DeltaUserChange.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x02\n" +
	"\tDeltaSync\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vserver_code\x18\x02 \x01(\tR\n" +
	"serverCode\x12,\n" +
	"\x06kernel\x18\x03 \x01(\x0e2\x14.agent.v1.KernelTypeR\x06kernel\x126\n" +
	"\tadd_users\x18\x04 \x03(\v2\x19.agent.v1.DeltaUserChangeR\baddUsers\x12\x1b\n" +
	"\tdel_users\x18\x05 \x03(\tR\bdelUsers\x12%\n" +
	"\x0econfig_version\x18\x06 \x01(\x03R\rconfigVersion\x12\x1f\n" +
	"\vconfig_hash\x18\a \x01(\tR\n" +
	"configHash\"\x8d\x01\n" +
	"\bDeltaAck\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x03R\rconfigVersion\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12*\n" +
	"\x11apply_duration_ms\x18\x04 \x01(\x03R\x0fapplyDurationMs\"\xe3\x01\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x126\n" +
	"\x06labels\x18\x05 \x03(\v2\x1e.agent.v1.LogEntry.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\bLogChunk\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.agent.v1.LogEntryR\aentries\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\"\xb8\x03\n" +
	"\fAgentMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12+\n" +
	"\x04auth\x18\x03 \x01(\v2\x15.agent.v1.AuthRequestH\x00R\x04auth\x123\n" +
	"\theartbeat\x18\x04 \x01(\v2\x13.agent.v1.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\rconfig_result\x18\x05 \x01(\v2\x16.agent.v1.ConfigResultH\x00R\fconfigResult\x12@\n" +
	"\x0etraffic_report\x18\x06 \x01(\v2\x17.agent.v1.TrafficReportH\x00R\rtrafficReport\x12$\n" +
	"\x04ping\x18\a \x01(\v2\x0e.agent.v1.PingH\x00R\x04ping\x121\n" +
	"\tlog_chunk\x18\b \x01(\v2\x12.agent.v1.LogChunkH\x00R\blogChunk\x121\n" +
	"\tdelta_ack\x18\t \x01(\v2\x12.agent.v1.DeltaAckH\x00R\bdeltaAckB\t\n" +
	"\apayload\"\x81\x04\n" +
	"\fPanelMessage\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12.\n" +
	"\bauth_ack\x18\x03 \x01(\v2\x11.agent.v1.AuthAckH\x00R\aauthAck\x12=\n" +
	"\rheartbeat_ack\x18\x04 \x01(\v2\x16.agent.v1.HeartbeatAckH\x00R\fheartbeatAck\x127\n" +
	"\vconfig_push\x18\x05 \x01(\v2\x14.agent.v1.ConfigPushH\x00R\n" +
	"configPush\x124\n" +
	"\buser_ban\x18\x06 \x01(\v2\x17.agent.v1.UserBanNoticeH\x00R\auserBan\x12:\n" +
	"\n" +
	"cert_renew\x18\a \x01(\v2\x19.agent.v1.CertRenewNoticeH\x00R\tcertRenew\x12$\n" +
	"\x04pong\x18\b \x01(\v2\x0e.agent.v1.PongH\x00R\x04pong\x12@\n" +
	"\vmaintenance\x18\t \x01(\v2\x1c.agent.v1.MaintenanceCommandH\x00R\vmaintenance\x124\n" +
	"\n" +
	"delta_sync\x18\n" +
	" \x01(\v2\x13.agent.v1.DeltaSyncH\x00R\tdeltaSyncB\t\n" +
	"\apayload*}\n" +
	"\fChannelState\x12\x19\n" +
	"\x15CHANNEL_STATE_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15CHANNEL_STATE_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16CHANNEL_STATE_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17CHANNEL_STATE_UNHEALTHY\x10\x03*X\n" +
	"\n" +
	"KernelType\x12\x1b\n" +
	"\x17KERNEL_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10KERNEL_TYPE_XRAY\x10\x01\x12\x17\n" +
	"\x13KERNEL_TYPE_SINGBOX\x10\x02*\xa7\x01\n" +
	"\x0fHeartbeatAction\x12\x19\n" +
	"\x15HEARTBEAT_ACTION_NONE\x10\x00\x12\x1b\n" +
	"\x17HEARTBEAT_ACTION_RELOAD\x10\x01\x12\x1c\n" +
	"\x18HEARTBEAT_ACTION_RESTART\x10\x02\x12 \n" +
	"\x1cHEARTBEAT_ACTION_MAINTENANCE\x10\x03\x12\x1c\n" +
	"\x18HEARTBEAT_ACTION_UPGRADE\x10\x042L\n" +
	"\fAgentChannel\x12<\n" +
	"\x06Stream\x12\x16.agent.v1.AgentMessage\x1a\x16.agent.v1.PanelMessage(\x010\x01B\x8e\x01\n" +
	"\fcom.agent.v1B\fChannelProtoP\x01Z/github.com/airport-panel/proto/agent/v1;agentv1\xa2\x02\x03AXX\xaa\x02\bAgent.V1\xca\x02\bAgent\\V1\xe2\x02\x14Agent\\V1\\GPBMetadata\xea\x02\tAgent::V1b\x06proto3"

var (
	file_agent_v1_channel_proto_rawDescOnce sync.Once
	file_agent_v1_channel_proto_rawDescData []byte
)

func file_agent_v1_channel_proto_rawDescGZIP() []byte {
	file_agent_v1_channel_proto_rawDescOnce.Do(func() {
		file_agent_v1_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_channel_proto_rawDesc), len(file_agent_v1_channel_proto_rawDesc)))
	})
	return file_agent_v1_channel_proto_rawDescData
}

var file_agent_v1_channel_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_agent_v1_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_agent_v1_channel_proto_goTypes = []any{
	(ChannelState)(0),              // 0: agent.v1.ChannelState
	(KernelType)(0),                // 1: agent.v1.KernelType
	(HeartbeatAction)(0),           // 2: agent.v1.HeartbeatAction
	(MaintenanceCommand_Action)(0), // 3: agent.v1.MaintenanceCommand.Action
	(*ChannelHealth)(nil),          // 4: agent.v1.ChannelHealth
	(*ServerLoad)(nil),             // 5: agent.v1.ServerLoad
	(*KernelInfo)(nil),             // 6: agent.v1.KernelInfo
	(*NodeStatus)(nil),             // 7: agent.v1.NodeStatus
	(*UserTraffic)(nil),            // 8: agent.v1.UserTraffic
	(*AuthRequest)(nil),            // 9: agent.v1.AuthRequest
	(*AuthAck)(nil),                // 10: agent.v1.AuthAck
	(*Heartbeat)(nil),              // 11: agent.v1.Heartbeat
	(*HeartbeatAck)(nil),           // 12: agent.v1.HeartbeatAck
	(*NodeSpec)(nil),               // 13: agent.v1.NodeSpec
	(*ConfigPush)(nil),             // 14: agent.v1.ConfigPush
	(*ConfigResult)(nil),           // 15: agent.v1.ConfigResult
	(*TrafficReport)(nil),          // 16: agent.v1.TrafficReport
	(*UserBanNotice)(nil),          // 17: agent.v1.UserBanNotice
	(*CertRenewNotice)(nil),        // 18: agent.v1.CertRenewNotice
	(*Ping)(nil),                   // 19: agent.v1.Ping
	(*Pong)(nil),                   // 20: agent.v1.Pong
	(*MaintenanceCommand)(nil),     // 21: agent.v1.MaintenanceCommand
	(*DeltaUserChange)(nil),        // 22: agent.v1.DeltaUserChange
	(*DeltaSync)(nil),              // 23: agent.v1.DeltaSync
	(*DeltaAck)(nil),               // 24: agent.v1.DeltaAck
	(*LogEntry)(nil),               // 25: agent.v1.LogEntry
	(*LogChunk)(nil),               // 26: agent.v1.LogChunk
	(*AgentMessage)(nil),           // 27: agent.v1.AgentMessage
	(*PanelMessage)(nil),           // 28: agent.v1.PanelMessage
	nil,                            // 29: agent.v1.DeltaUserChange.ExtraEntry
	nil,                            // 30: agent.v1.LogEntry.LabelsEntry
}
var file_agent_v1_channel_proto_depIdxs = []int32{
	0,  // 0: agent.v1.ChannelHealth.state:type_name -> agent.v1.ChannelState
	1,  // 1: agent.v1.KernelInfo.type:type_name -> agent.v1.KernelType
	1,  // 2: agent.v1.AuthRequest.preferred_kernel:type_name -> agent.v1.KernelType
	5,  // 3: agent.v1.Heartbeat.load:type_name -> agent.v1.ServerLoad
	6,  // 4: agent.v1.Heartbeat.kernel:type_name -> agent.v1.KernelInfo
	7,  // 5: agent.v1.Heartbeat.nodes:type_name -> agent.v1.NodeStatus
	4,  // 6: agent.v1.Heartbeat.channel:type_name -> agent.v1.ChannelHealth
	2,  // 7: agent.v1.HeartbeatAck.action:type_name -> agent.v1.HeartbeatAction
	13, // 8: agent.v1.ConfigPush.nodes:type_name -> agent.v1.NodeSpec
	8,  // 9: agent.v1.TrafficReport.entries:type_name -> agent.v1.UserTraffic
	3,  // 10: agent.v1.MaintenanceCommand.action:type_name -> agent.v1.MaintenanceCommand.Action
	29, // 11: agent.v1.DeltaUserChange.extra:type_name -> agent.v1.DeltaUserChange.ExtraEntry
	1,  // 12: agent.v1.DeltaSync.kernel:type_name -> agent.v1.KernelType
	22, // 13: agent.v1.DeltaSync.add_users:type_name -> agent.v1.DeltaUserChange
	30, // 14: agent.v1.LogEntry.labels:type_name -> agent.v1.LogEntry.LabelsEntry
	25, // 15: agent.v1.LogChunk.entries:type_name -> agent.v1.LogEntry
	9,  // 16: agent.v1.AgentMessage.auth:type_name -> agent.v1.AuthRequest
	11, // 17: agent.v1.AgentMessage.heartbeat:type_name -> agent.v1.Heartbeat
	15, // 18: agent.v1.AgentMessage.config_result:type_name -> agent.v1.ConfigResult
	16, // 19: agent.v1.AgentMessage.traffic_report:type_name -> agent.v1.TrafficReport
	19, // 20: agent.v1.AgentMessage.ping:type_name -> agent.v1.Ping
	26, // 21: agent.v1.AgentMessage.log_chunk:type_name -> agent.v1.LogChunk
	24, // 22: agent.v1.AgentMessage.delta_ack:type_name -> agent.v1.DeltaAck
	10, // 23: agent.v1.PanelMessage.auth_ack:type_name -> agent.v1.AuthAck
	12, // 24: agent.v1.PanelMessage.heartbeat_ack:type_name -> agent.v1.HeartbeatAck
	14, // 25: agent.v1.PanelMessage.config_push:type_name -> agent.v1.ConfigPush
	17, // 26: agent.v1.PanelMessage.user_ban:type_name -> agent.v1.UserBanNotice
	18, // 27: agent.v1.PanelMessage.cert_renew:type_name -> agent.v1.CertRenewNotice
	20, // 28: agent.v1.PanelMessage.pong:type_name -> agent.v1.Pong
	21, // 29: agent.v1.PanelMessage.maintenance:type_name -> agent.v1.MaintenanceCommand
	23, // 30: agent.v1.PanelMessage.delta_sync:type_name -> agent.v1.DeltaSync
	27, // 31: agent.v1.AgentChannel.Stream:input_type -> agent.v1.AgentMessage
	28, // 32: agent.v1.AgentChannel.Stream:output_type -> agent.v1.PanelMessage
	32, // [32:33] is the sub-list for method output_type
	31, // [31:32] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_agent_v1_channel_proto_init() }
func file_agent_v1_channel_proto_init() {
	if File_agent_v1_channel_proto != nil {
		return
	}
	file_agent_v1_channel_proto_msgTypes[23].OneofWrappers = []any{
		(*AgentMessage_Auth)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_ConfigResult)(nil),
		(*AgentMessage_TrafficReport)(nil),
		(*AgentMessage_Ping)(nil),
		(*AgentMessage_LogChunk)(nil),
		(*AgentMessage_DeltaAck)(nil),
	}
	file_agent_v1_channel_proto_msgTypes[24].OneofWrappers = []any{
		(*PanelMessage_AuthAck)(nil),
		(*PanelMessage_HeartbeatAck)(nil),
		(*PanelMessage_ConfigPush)(nil),
		(*PanelMessage_UserBan)(nil),
		(*PanelMessage_CertRenew)(nil),
		(*PanelMessage_Pong)(nil),
		(*PanelMessage_Maintenance)(nil),
		(*PanelMessage_DeltaSync)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_channel_proto_rawDesc), len(file_agent_v1_channel_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_channel_proto_goTypes,
		DependencyIndexes: file_agent_v1_channel_proto_depIdxs,
		EnumInfos:         file_agent_v1_channel_proto_enumTypes,
		MessageInfos:      file_agent_v1_channel_proto_msgTypes,
	}.Build()
	File_agent_v1_channel_proto = out.File
	file_agent_v1_channel_proto_goTypes = nil
	file_agent_v1_channel_proto_depIdxs = nil
}
