// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agent/v1/channel.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentChannel_Stream_FullMethodName = "/agent.v1.AgentChannel/Stream"
)

// AgentChannelClient is the client API for AgentChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ============================================================================
// AgentChannel 是 Agent<->Panel 的双向流通信服务
// Agent 作为 gRPC Client 主动连接 Panel，建立双向流后：
//   - Agent 发送: Auth, Heartbeat, ConfigResult, TrafficReport, Ping
//   - Panel 发送: AuthAck, HeartbeatAck, ConfigPush, Pong, UserBanNotice, CertRenewNotice
//
// 所有消息带单调递增 seq 号用于防重放和排序
// ============================================================================
type AgentChannelClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, PanelMessage], error)
}

type agentChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentChannelClient(cc grpc.ClientConnInterface) AgentChannelClient {
	return &agentChannelClient{cc}
}

func (c *agentChannelClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, PanelMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentChannel_ServiceDesc.Streams[0], AgentChannel_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, PanelMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_StreamClient = grpc.BidiStreamingClient[AgentMessage, PanelMessage]

// AgentChannelServer is the server API for AgentChannel service.
// All implementations must embed UnimplementedAgentChannelServer
// for forward compatibility.
//
// ============================================================================
// AgentChannel 是 Agent<->Panel 的双向流通信服务
// Agent 作为 gRPC Client 主动连接 Panel，建立双向流后：
//   - Agent 发送: Auth, Heartbeat, ConfigResult, TrafficReport, Ping
//   - Panel 发送: AuthAck, HeartbeatAck, ConfigPush, Pong, UserBanNotice, CertRenewNotice
//
// 所有消息带单调递增 seq 号用于防重放和排序
// ============================================================================
type AgentChannelServer interface {
	Stream(grpc.BidiStreamingServer[AgentMessage, PanelMessage]) error
	mustEmbedUnimplementedAgentChannelServer()
}

// UnimplementedAgentChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentChannelServer struct{}

func (UnimplementedAgentChannelServer) Stream(grpc.BidiStreamingServer[AgentMessage, PanelMessage]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedAgentChannelServer) mustEmbedUnimplementedAgentChannelServer() {}
func (UnimplementedAgentChannelServer) testEmbeddedByValue()                      {}

// UnsafeAgentChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentChannelServer will
// result in compilation errors.
type UnsafeAgentChannelServer interface {
	mustEmbedUnimplementedAgentChannelServer()
}

func RegisterAgentChannelServer(s grpc.ServiceRegistrar, srv AgentChannelServer) {
	// If the following call panics, it indicates UnimplementedAgentChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentChannel_ServiceDesc, srv)
}

func _AgentChannel_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentChannelServer).Stream(&grpc.GenericServerStream[AgentMessage, PanelMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_StreamServer = grpc.BidiStreamingServer[AgentMessage, PanelMessage]

// AgentChannel_ServiceDesc is the grpc.ServiceDesc for AgentChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentChannel",
	HandlerType: (*AgentChannelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _AgentChannel_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent/v1/channel.proto",
}
