// Package nginxrender 生成 Xray InboundGroup 架构所需的 nginx 增量配置片段。
//
// 核心原则：
//   - 生成物是独立 snippet 文件，通过 include 引入现有 nginx 配置
//   - 绝不直接改写用户已有配置（宝塔面板管理的 vhost 文件等）
//   - 可以通过删除 snippet 文件单独禁用，不影响主配置
//
// 两个产出：
//   - yundu-stream-snippet.conf：stream SNI 分流规则片段（map 条目，include 到 map 内部）
//   - yundu-https-snippet.conf：CDN 反代 vhost server 块（grpc_pass 到 XHTTP internal inbound）
package nginxrender

import (
	"fmt"
	"strings"

	"github.com/airport-panel/subscription/inboundgroup"
	"github.com/airport-panel/subscription/nodespec"
)

// SnippetConfig 渲染配置，描述目标 VPS 的 nginx 环境参数。
type SnippetConfig struct {
	// HTTPSListenPort nginx HTTPS vhost 监听端口（VPS190 实测为 8445）
	HTTPSListenPort int
	// XHTTPInternalPort XHTTP internal inbound 监听的 TCP 端口（nginx grpc_pass 目标）
	// 注意：不能使用 Xray 的 abstract unix socket（@name），因为 nginx 作为外部进程无法引用
	// 生产环境中 Xray 的 internal inbound 必须监听真实 TCP 端口（如 127.0.0.1:8446）
	XHTTPInternalPort int
	// SNIHosts 需要追加到 SNI 分流的域名列表（已有域名不需要重复添加）
	SNIHosts []string
	// UpstreamName CDN 反代 upstream 名称
	UpstreamName string
}

// DefaultConfig 返回基于 VPS190 实测的默认配置。
func DefaultConfig() *SnippetConfig {
	return &SnippetConfig{
		HTTPSListenPort:   8445,
		XHTTPInternalPort: 8446,
		UpstreamName:      "yundu_xhttp_backend",
	}
}

// RenderStreamConf 生成 stream SNI 分流规则片段。
//
// 产出格式（map 条目列表，用于 include 到现有 map 块内部）：
//
//	# yundu-stream-snippet.conf (auto-generated, do not edit manually)
//	# 通过 include 引入到 stream map 块内部
//	~^cdn-domain1\.example\.com$ yundu_xhttp_backend;
//	~^cdn-domain2\.example\.com$ yundu_xhttp_backend;
//
// 注意：不重复定义 map/upstream/server，只生成 map 条目。
// 现有 443_ssl_preread.conf 中的 map 需要添加 include 指令来引入此片段。
func RenderStreamConf(groups []*inboundgroup.InboundGroup, cfg *SnippetConfig) string {
	if cfg == nil {
		cfg = DefaultConfig()
	}

	var buf strings.Builder
	buf.WriteString("# yundu-stream-snippet.conf (auto-generated by YunDu nginxrender)\n")
	buf.WriteString("# 通过 include 引入到 stream map 块内部，不要直接修改主配置\n")
	buf.WriteString(fmt.Sprintf("# upstream %s 需在主配置中定义（指向 127.0.0.1:%d）\n",
		cfg.UpstreamName, cfg.HTTPSListenPort))
	buf.WriteString("# 生成时间: 自动\n\n")

	// 为每个 SNI 域名生成 map 条目
	for _, host := range cfg.SNIHosts {
		if host == "" {
			continue
		}
		// 转义为 nginx regex（. → \.）
		regexHost := strings.ReplaceAll(host, ".", `\.`)
		buf.WriteString(fmt.Sprintf("~^%s$ %s;\n", regexHost, cfg.UpstreamName))
	}

	if len(cfg.SNIHosts) == 0 {
		buf.WriteString("# (无 SNI 域名配置，空 snippet)\n")
	}

	return buf.String()
}

// RenderHTTPSConf 生成 CDN 反代 vhost 片段。
//
// 产出格式（独立 server 块，通过 http include 引入）：
//
//	# yundu-https-snippet.conf (auto-generated)
//	# CDN 反代：将 XHTTP path 流量 grpc_pass 到 internal inbound
//	server {
//	    listen 8445 ssl http2;
//	    server_name cdn-domain.example.com;
//	    # TLS 证书（复用现有证书路径）
//	    ssl_certificate /path/to/cert.pem;
//	    ssl_certificate_key /path/to/key.pem;
//
//	    # XHTTP packet-up CDN 模式：grpc_pass 到 internal inbound
//	    location /xhttp-path {
//	        grpc_pass grpc://@xhttp-internal;
//	        grpc_set_header Host $host;
//	        grpc_read_timeout 300s;
//	    }
//	}
//
// 注意：
//   - 监听端口必须复用现有 8445（不能自行另起端口）
//   - TLS 证书路径由调用方提供（从 DB 证书表读取）
//   - 每个 XHTTP fallback 节点生成一个 location 块
func RenderHTTPSConf(groups []*inboundgroup.InboundGroup, cfg *SnippetConfig, certPath, keyPath string) string {
	if cfg == nil {
		cfg = DefaultConfig()
	}

	var buf strings.Builder
	buf.WriteString("# yundu-https-snippet.conf (auto-generated by YunDu nginxrender)\n")
	buf.WriteString("# CDN 反代 vhost：将 XHTTP path 流量 grpc_pass 到 internal inbound\n")
	buf.WriteString("# 通过 include 引入到 http 块，不要直接修改主配置\n\n")

	// 为每个 SNI 域名生成 server 块
	for _, host := range cfg.SNIHosts {
		if host == "" {
			continue
		}
		buf.WriteString(fmt.Sprintf("server {\n"))
		// nginx 1.24.x 使用 listen ... ssl http2 语法（1.25+ 才支持 http2 on 独立指令）
		buf.WriteString(fmt.Sprintf("    listen %d ssl http2;\n", cfg.HTTPSListenPort))
		buf.WriteString(fmt.Sprintf("    server_name %s;\n", host))
		buf.WriteString(fmt.Sprintf("\n"))

		if certPath != "" && keyPath != "" {
			buf.WriteString(fmt.Sprintf("    ssl_certificate %s;\n", certPath))
			buf.WriteString(fmt.Sprintf("    ssl_certificate_key %s;\n", keyPath))
			buf.WriteString(fmt.Sprintf("    ssl_protocols TLSv1.2 TLSv1.3;\n"))
			buf.WriteString(fmt.Sprintf("\n"))
		}

		// 为每个 InboundGroup 的 internal inbound 生成 location 块
		// 注意：nginx 不能直接引用 Xray 的 abstract unix socket（@name），
		// 必须使用 XHTTPInternalPort（真实 TCP 端口）
		grpcTarget := fmt.Sprintf("127.0.0.1:%d", cfg.XHTTPInternalPort)
		for _, group := range groups {
			if group == nil {
				continue
			}
			for _, internal := range group.Internal {
				if internal == nil {
					continue
				}
				// 从 internal inbound 提取 path
				path := extractPathFromSettings(internal.Settings)
				if path == "" {
					path = "/" // 默认 path
				}
				buf.WriteString(fmt.Sprintf("    # %s (internal TCP port %d)\n", internal.Tag, cfg.XHTTPInternalPort))
				buf.WriteString(fmt.Sprintf("    location %s {\n", path))
				buf.WriteString(fmt.Sprintf("        grpc_pass grpc://%s;\n", grpcTarget))
				buf.WriteString(fmt.Sprintf("        grpc_set_header Host $host;\n"))
				buf.WriteString(fmt.Sprintf("        grpc_set_header X-Real-IP $remote_addr;\n"))
				buf.WriteString(fmt.Sprintf("        grpc_read_timeout 300s;\n"))
				buf.WriteString(fmt.Sprintf("        grpc_send_timeout 300s;\n"))
				buf.WriteString(fmt.Sprintf("    }\n"))
			}
		}

		buf.WriteString(fmt.Sprintf("}\n\n"))
	}

	if len(cfg.SNIHosts) == 0 {
		buf.WriteString("# (无 SNI 域名配置，空 snippet)\n")
	}

	return buf.String()
}

// extractPathFromSettings 从 internal inbound 的 settings 中提取 path。
func extractPathFromSettings(settings map[string]interface{}) string {
	if settings == nil {
		return ""
	}
	// 尝试从 stream.network/xhttpSettings.path 获取
	if stream, ok := settings["stream"].(map[string]interface{}); ok {
		if xhttp, ok := stream["xhttpSettings"].(map[string]interface{}); ok {
			if path, ok := xhttp["path"].(string); ok {
				return path
			}
		}
	}
	return ""
}

// RenderUpstreamBlock 生成 upstream 定义块（用于补充到主配置）。
//
// 产出格式：
//
//	upstream yundu_xhttp_backend {
//	    server 127.0.0.1:8445;
//	}
func RenderUpstreamBlock(cfg *SnippetConfig) string {
	if cfg == nil {
		cfg = DefaultConfig()
	}
	return fmt.Sprintf(`upstream %s {
    server 127.0.0.1:%d;
}
`, cfg.UpstreamName, cfg.HTTPSListenPort)
}

// RenderGroupedStreamConfig 生成完整的 stream 配置片段（含 upstream + map + server）。
//
// 用于新部署的 VPS（没有现有 443_ssl_preread.conf 的情况）。
// 已有 stream 配置的 VPS 应使用 RenderStreamConf（仅 map 条目）。
func RenderGroupedStreamConfig(groups []*inboundgroup.InboundGroup, cfg *SnippetConfig) string {
	if cfg == nil {
		cfg = DefaultConfig()
	}

	var buf strings.Builder
	buf.WriteString("# yundu-stream-grouped.conf (auto-generated by YunDu nginxrender)\n")
	buf.WriteString("# 完整 stream SNI 分流配置（用于新部署 VPS）\n\n")

	// upstream 定义
	buf.WriteString(fmt.Sprintf("upstream %s {\n", cfg.UpstreamName))
	buf.WriteString(fmt.Sprintf("    server 127.0.0.1:%d;\n", cfg.HTTPSListenPort))
	buf.WriteString("}\n\n")

	// SNI 分流 map
	buf.WriteString(fmt.Sprintf("map $ssl_preread_server_name $yundu_backend {\n"))
	buf.WriteString("    default yundu_xray_backend;\n")
	for _, host := range cfg.SNIHosts {
		if host == "" {
			continue
		}
		regexHost := strings.ReplaceAll(host, ".", `\.`)
		buf.WriteString(fmt.Sprintf("    ~^%s$ %s;\n", regexHost, cfg.UpstreamName))
	}
	buf.WriteString("}\n\n")

	// stream server 块
	buf.WriteString("server {\n")
	buf.WriteString("    listen 443;\n")
	buf.WriteString("    ssl_preread on;\n")
	buf.WriteString("    proxy_pass $yundu_backend;\n")
	buf.WriteString("    proxy_timeout 300s;\n")
	buf.WriteString("    proxy_connect_timeout 10s;\n")
	buf.WriteString("}\n")

	return buf.String()
}

// ValidateSnippetConfig 校验配置参数完整性。
func ValidateSnippetConfig(cfg *SnippetConfig) error {
	if cfg == nil {
		return fmt.Errorf("snippet config is nil")
	}
	if cfg.HTTPSListenPort < 1 || cfg.HTTPSListenPort > 65535 {
		return fmt.Errorf("invalid HTTPS listen port: %d", cfg.HTTPSListenPort)
	}
	if cfg.XHTTPInternalPort < 1 || cfg.XHTTPInternalPort > 65535 {
		return fmt.Errorf("invalid XHTTP internal port: %d", cfg.XHTTPInternalPort)
	}
	if cfg.UpstreamName == "" {
		return fmt.Errorf("upstream name is empty")
	}
	return nil
}

// ExtractSNIHostsFromSpecs 从 NodeSpec 列表中提取需要 CDN 代理的 SNI 域名。
// 规则：XHTTP+TLS（CDN 模式）节点的 SNI 域名需要加入 SNI 分流。
func ExtractSNIHostsFromSpecs(specs []*nodespec.NodeSpec) []string {
	seen := make(map[string]bool)
	var hosts []string
	for _, spec := range specs {
		if spec == nil || spec.Transport.Type != nodespec.TransportXHTTP {
			continue
		}
		if spec.Security != nodespec.SecurityTLS {
			continue // CDN 模式必须是 TLS
		}
		if spec.TLS == nil || spec.TLS.SNI == "" {
			continue
		}
		if !seen[spec.TLS.SNI] {
			seen[spec.TLS.SNI] = true
			hosts = append(hosts, spec.TLS.SNI)
		}
	}
	return hosts
}

// WSVhostEntry 描述一个 WS/gRPC/HTTPUpgrade CDN 节点的 vhost 配置项。
// 用于 CF CDN → nginx 8445/8446 → proxy_pass/grpc_pass → xray 内部端口的链路。
type WSVhostEntry struct {
	// ServerName CDN 域名（如 us.tiktokplay.na.am）
	ServerName string `json:"server_name"`
	// WSPath WebSocket/gRPC/HTTPUpgrade/XHTTP path（如 /ws9ad966ec 或 /grpc14ff1141）
	WSPath string `json:"ws_path"`
	// InternalPort xray 内部监听端口（如 40013）
	InternalPort int `json:"internal_port"`
	// CertPath SSL 证书路径（可选，per-domain 覆盖 certPath 参数）
	// 宝塔环境典型值：/www/server/panel/vhost/cert/{domain}/fullchain.pem
	CertPath string `json:"cert_path,omitempty"`
	// KeyPath SSL 私钥路径（可选，per-domain 覆盖 keyPath 参数）
	// 宝塔环境典型值：/www/server/panel/vhost/cert/{domain}/privkey.pem
	KeyPath string `json:"key_path,omitempty"`
	// IsGRPC 标记为 gRPC 服务（使用 grpc_pass 而非 proxy_pass，需要 HTTP/2）
	IsGRPC bool `json:"is_grpc,omitempty"`
	// IsHTTPUpgrade 标记为 HTTPUpgrade 服务（使用 proxy_pass + Upgrade 头，HTTP/1.1）
	IsHTTPUpgrade bool `json:"is_http_upgrade,omitempty"`
	// IsXHTTP 标记为 XHTTP 服务（使用 proxy_pass 无 Upgrade + proxy_buffering off）
	// 合并渲染时与 WS/gRPC/HTTPUpgrade 共存于同一 server 块，避免 conflicting server_name
	IsXHTTP bool `json:"is_xhttp,omitempty"`
	// UpPath XHTTP split 模式上行 path（可选，仅 IsXHTTP=true 时有效）
	// 非空且不等于 WSPath 时生成独立 location（proxy_buffering on）
	UpPath string `json:"up_path,omitempty"`
	// DownPath XHTTP split 模式下行 path（可选，仅 IsXHTTP=true 时有效）
	// 非空且不等于 WSPath 时生成独立 location（proxy_buffering off 流式传输）
	DownPath string `json:"down_path,omitempty"`
}

// RenderWSVhostConf 生成 WS CDN 反代 vhost 片段。
//
// 产出格式（独立 server 块，通过 http include 引入）：
//
//	# yundu-https-ws-snippet.conf (auto-generated)
//	server {
//	    listen 8445 ssl;
//	    http2 on;
//	    server_name us.tiktokplay.na.am;
//	    ssl_certificate /www/server/panel/vhost/cert/us.tiktokplay.na.am/fullchain.pem;
//	    ssl_certificate_key /www/server/panel/vhost/cert/us.tiktokplay.na.am/privkey.pem;
//	    ssl_protocols TLSv1.2 TLSv1.3;
//
//	    location /ws9ad966ec {
//	        proxy_pass http://127.0.0.1:40013;
//	        proxy_http_version 1.1;
//	        proxy_set_header Upgrade $http_upgrade;
//	        proxy_set_header Connection "upgrade";
//	        proxy_set_header Host $host;
//	        proxy_set_header X-Real-IP $remote_addr;
//	        proxy_read_timeout 300s;
//	        proxy_send_timeout 300s;
//	    }
//	}
//
// 按 ServerName 分组：同一域名的多个 WS path 合并到同一 server 块。
// 证书路径优先使用 WSVhostEntry.CertPath/KeyPath（per-domain），为空时回退到 certPath/keyPath 参数。
//
// P1-2 修复：按 (ServerName, WSPath) 复合键去重。
// 旧逻辑仅按 ServerName 分组，同一域名下相同 path 的多节点会生成重复 location 块，
// 导致 nginx -t 报 "duplicate location" 错误。现在同一 (ServerName, WSPath) 只保留第一条。
func RenderWSVhostConf(entries []*WSVhostEntry, cfg *SnippetConfig, certPath, keyPath string) string {
	if cfg == nil {
		cfg = DefaultConfig()
	}
	if len(entries) == 0 {
		return ""
	}

	// 按 ServerName 分组，同时记录 per-domain 证书路径和是否包含 gRPC
	type pathPort struct {
		Path          string
		Port          int
		IsGRPC        bool
		IsHTTPUpgrade bool
		IsXHTTP       bool
		UpPath        string
		DownPath      string
	}
	type serverGroup struct {
		Paths     []pathPort
		CertPath  string
		KeyPath   string
		HasGRPC   bool
		HasStream bool // WS 或 HTTPUpgrade（HTTP/1.1 流式）
		// P1-2: 复合键去重集合，key = WSPath
		seenPaths map[string]bool
	}
	grouped := make(map[string]*serverGroup)
	var serverNames []string
	for _, e := range entries {
		if e == nil || e.ServerName == "" || e.WSPath == "" || e.InternalPort == 0 {
			continue
		}
		pp := pathPort{
			Path:          e.WSPath,
			Port:          e.InternalPort,
			IsGRPC:        e.IsGRPC,
			IsHTTPUpgrade: e.IsHTTPUpgrade,
			IsXHTTP:       e.IsXHTTP,
			UpPath:        e.UpPath,
			DownPath:      e.DownPath,
		}
		if g, ok := grouped[e.ServerName]; !ok {
			serverNames = append(serverNames, e.ServerName)
			grouped[e.ServerName] = &serverGroup{
				Paths:     []pathPort{pp},
				CertPath:  e.CertPath,
				KeyPath:   e.KeyPath,
				HasGRPC:   e.IsGRPC,
				HasStream: !e.IsGRPC, // WS/HTTPUpgrade/XHTTP 是 HTTP/1.1 流式
				seenPaths: map[string]bool{e.WSPath: true},
			}
		} else {
			// P1-2: 复合键去重 — 同一 (ServerName, WSPath) 只保留第一条
			if g.seenPaths[e.WSPath] {
				continue
			}
			g.seenPaths[e.WSPath] = true
			g.Paths = append(g.Paths, pp)
			if e.IsGRPC {
				g.HasGRPC = true
			} else {
				g.HasStream = true
			}
			// 如果新条目有证书路径而旧的没有，则更新
			if g.CertPath == "" && e.CertPath != "" {
				g.CertPath = e.CertPath
			}
			if g.KeyPath == "" && e.KeyPath != "" {
				g.KeyPath = e.KeyPath
			}
		}
	}

	if len(serverNames) == 0 {
		return ""
	}

	var buf strings.Builder
	buf.WriteString("# yundu-https-ws-snippet.conf (auto-generated by YunDu nginxrender)\n")
	buf.WriteString("# WS CDN 反代 vhost：proxy_pass 到 xray 内部端口\n")
	buf.WriteString("# 通过 include 引入到 http 块，不要直接修改主配置\n\n")

	for _, sn := range serverNames {
		g := grouped[sn]
		buf.WriteString("server {\n")
		// nginx 1.24.x 使用 listen ... ssl http2 语法（1.25+ 才支持 http2 on 独立指令）
		// gRPC 必须启用 http2（grpc_pass 需要 HTTP/2）；纯 WS/XHTTP/HTTPUpgrade 使用 HTTP/1.1（CF 已关闭 HTTP/2 to Origin）
		// 混合场景（同域名既有 gRPC 又有 XHTTP）：启用 http2（h2 向后兼容 h1，优先保证 gRPC 可用）
		listenOpts := ""
		if g.HasGRPC {
			listenOpts = " http2"
		}
		buf.WriteString(fmt.Sprintf("    listen %d ssl%s;\n", cfg.HTTPSListenPort, listenOpts))
		buf.WriteString(fmt.Sprintf("    server_name %s;\n\n", sn))

		// 证书路径：优先 per-domain，回退到 shared 参数
		effectiveCert := g.CertPath
		if effectiveCert == "" {
			effectiveCert = certPath
		}
		effectiveKey := g.KeyPath
		if effectiveKey == "" {
			effectiveKey = keyPath
		}
		if effectiveCert != "" && effectiveKey != "" {
			buf.WriteString(fmt.Sprintf("    ssl_certificate %s;\n", effectiveCert))
			buf.WriteString(fmt.Sprintf("    ssl_certificate_key %s;\n", effectiveKey))
			buf.WriteString("    ssl_protocols TLSv1.2 TLSv1.3;\n")
			buf.WriteString("    ssl_ciphers EECDH+CHACHA20:EECDH+AES128:EECDH+AES256:!MD5;\n")
			buf.WriteString("    ssl_prefer_server_ciphers on;\n")
			buf.WriteString("    ssl_session_cache shared:SSL:10m;\n")
			buf.WriteString("    ssl_session_timeout 10m;\n\n")
		}

		// Cloudflare 真实 IP（CDN 场景必须，否则 xray 看到的是 CF 节点 IP）
		buf.WriteString("    # Cloudflare 真实IP\n")
		buf.WriteString("    set_real_ip_from 103.21.244.0/22;\n")
		buf.WriteString("    set_real_ip_from 103.22.200.0/22;\n")
		buf.WriteString("    set_real_ip_from 103.31.4.0/22;\n")
		buf.WriteString("    set_real_ip_from 104.16.0.0/13;\n")
		buf.WriteString("    set_real_ip_from 104.24.0.0/14;\n")
		buf.WriteString("    set_real_ip_from 108.162.192.0/18;\n")
		buf.WriteString("    set_real_ip_from 131.0.72.0/22;\n")
		buf.WriteString("    set_real_ip_from 141.101.64.0/18;\n")
		buf.WriteString("    set_real_ip_from 162.158.0.0/15;\n")
		buf.WriteString("    set_real_ip_from 172.64.0.0/13;\n")
		buf.WriteString("    set_real_ip_from 173.245.48.0/20;\n")
		buf.WriteString("    set_real_ip_from 188.114.96.0/20;\n")
		buf.WriteString("    set_real_ip_from 190.93.240.0/22;\n")
		buf.WriteString("    set_real_ip_from 197.234.240.0/22;\n")
		buf.WriteString("    set_real_ip_from 198.41.128.0/17;\n")
		buf.WriteString("    real_ip_header CF-Connecting-IP;\n")
		buf.WriteString("    real_ip_recursive on;\n\n")

		for _, pp := range g.Paths {
			if pp.IsGRPC {
				// gRPC serviceName 可能不带 / 前缀，但 nginx location 必须以 / 开头
				grpcLocPath := pp.Path
				if !strings.HasPrefix(grpcLocPath, "/") {
					grpcLocPath = "/" + grpcLocPath
				}
				buf.WriteString(fmt.Sprintf("    # gRPC → 127.0.0.1:%d\n", pp.Port))
				buf.WriteString(fmt.Sprintf("    location %s {\n", grpcLocPath))
				buf.WriteString(fmt.Sprintf("        grpc_pass grpc://127.0.0.1:%d;\n", pp.Port))
				buf.WriteString("        grpc_set_header Host $host;\n")
				buf.WriteString("        grpc_set_header X-Real-IP $remote_addr;\n")
				buf.WriteString("        grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
				buf.WriteString("        grpc_read_timeout 300s;\n")
				buf.WriteString("        grpc_send_timeout 300s;\n")
				buf.WriteString("        grpc_buffer_size 16k;\n")
			} else if pp.IsXHTTP {
				// XHTTP：proxy_pass 无 Upgrade + proxy_buffering off（流式传输）
				buf.WriteString(fmt.Sprintf("    # XHTTP -> 127.0.0.1:%d\n", pp.Port))
				buf.WriteString(fmt.Sprintf("    location %s {\n", pp.Path))
				buf.WriteString(fmt.Sprintf("        proxy_pass http://127.0.0.1:%d;\n", pp.Port))
				buf.WriteString("        proxy_http_version 1.1;\n")
				buf.WriteString("        proxy_set_header Host $host;\n")
				buf.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
				buf.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
				buf.WriteString("        proxy_buffering off;\n")
				buf.WriteString("        proxy_request_buffering off;\n")
				buf.WriteString("        proxy_read_timeout 300s;\n")
				buf.WriteString("        proxy_send_timeout 300s;\n")
				buf.WriteString("    }\n")
				// XHTTP split 模式：upPath（上行，proxy_buffering on 允许缓冲）
				if pp.UpPath != "" && pp.UpPath != pp.Path {
					buf.WriteString(fmt.Sprintf("    # XHTTP split upPath -> 127.0.0.1:%d\n", pp.Port))
					buf.WriteString(fmt.Sprintf("    location %s {\n", pp.UpPath))
					buf.WriteString(fmt.Sprintf("        proxy_pass http://127.0.0.1:%d;\n", pp.Port))
					buf.WriteString("        proxy_http_version 1.1;\n")
					buf.WriteString("        proxy_set_header Host $host;\n")
					buf.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
					buf.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
					buf.WriteString("        proxy_buffering on;\n")
					buf.WriteString("        proxy_request_buffering on;\n")
					buf.WriteString("        proxy_read_timeout 300s;\n")
					buf.WriteString("        proxy_send_timeout 300s;\n")
					buf.WriteString("    }\n")
				}
				// XHTTP split 模式：downPath（下行，proxy_buffering off 流式传输）
				if pp.DownPath != "" && pp.DownPath != pp.Path {
					buf.WriteString(fmt.Sprintf("    # XHTTP split downPath -> 127.0.0.1:%d\n", pp.Port))
					buf.WriteString(fmt.Sprintf("    location %s {\n", pp.DownPath))
					buf.WriteString(fmt.Sprintf("        proxy_pass http://127.0.0.1:%d;\n", pp.Port))
					buf.WriteString("        proxy_http_version 1.1;\n")
					buf.WriteString("        proxy_set_header Host $host;\n")
					buf.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
					buf.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
					buf.WriteString("        proxy_buffering off;\n")
					buf.WriteString("        proxy_request_buffering off;\n")
					buf.WriteString("        proxy_read_timeout 300s;\n")
					buf.WriteString("        proxy_send_timeout 300s;\n")
					buf.WriteString("    }\n")
				}
				continue // XHTTP 已写完 } 和可选 split location，跳过下面的统一 }
			} else {
				// WS 和 HTTPUpgrade 都使用 proxy_pass + Upgrade 头
				buf.WriteString(fmt.Sprintf("    # %s → 127.0.0.1:%d\n", map[bool]string{true: "HTTPUpgrade", false: "WS"}[pp.IsHTTPUpgrade], pp.Port))
				buf.WriteString(fmt.Sprintf("    location %s {\n", pp.Path))
				buf.WriteString(fmt.Sprintf("        proxy_pass http://127.0.0.1:%d;\n", pp.Port))
				buf.WriteString("        proxy_http_version 1.1;\n")
				buf.WriteString("        proxy_set_header Upgrade $http_upgrade;\n")
				buf.WriteString("        proxy_set_header Connection \"upgrade\";\n")
				buf.WriteString("        proxy_set_header Host $host;\n")
				buf.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
				buf.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
				buf.WriteString("        proxy_read_timeout 300s;\n")
				buf.WriteString("        proxy_send_timeout 300s;\n")
			}
			buf.WriteString("    }\n")
		}

		// 默认 location：返回 404（防止路径扫描泄露信息）
		buf.WriteString("\n    # 默认返回 404\n    location / {\n        return 404;\n    }\n")
		buf.WriteString("}\n\n")
	}

	return buf.String()
}

// XHTTPVhostEntry 描述一个 XHTTP CDN 节点的 vhost 配置项。
// 用于 CF CDN → nginx 8445 → proxy_pass → xray XHTTP inbound 的链路。
// 与 WSVhostEntry 的区别：不使用 Upgrade/Connection 头，关闭 proxy_buffering 以支持流式传输。
type XHTTPVhostEntry struct {
	ServerName   string `json:"server_name"`
	XHTTPPath    string `json:"xhttp_path"`
	// UpPath/DownPath 用于 XHTTP split 模式（xhttp.mode=split）
	// split 模式下上行/下行分离为两个 path，nginx 需生成两个 location 块
	// UpPath 上行（客户端→服务器）：proxy_buffering on（允许缓冲）
	// DownPath 下行（服务器→客户端）：proxy_buffering off（流式传输）
	// 为空时仅生成 XHTTPPath 对应的单个 location（packet-up/stream-up 模式）
	UpPath       string `json:"up_path,omitempty"`
	DownPath     string `json:"down_path,omitempty"`
	InternalPort int    `json:"internal_port"`
	CertPath     string `json:"cert_path,omitempty"`
	KeyPath      string `json:"key_path,omitempty"`
}

// RenderXHTTPVhostConf 生成 XHTTP CDN 反代 vhost 片段。
// 与 RenderWSVhostConf 结构对齐，但 location 块使用 proxy_pass（无 Upgrade）+ proxy_buffering off。
// 按 ServerName 分组：同一域名的多个 XHTTP path 合并到同一 server 块。
func RenderXHTTPVhostConf(entries []*XHTTPVhostEntry, cfg *SnippetConfig, certPath, keyPath string) string {
	if cfg == nil {
		cfg = DefaultConfig()
	}
	if len(entries) == 0 {
		return ""
	}

	type pathPort struct {
		Path     string
		Port     int
		UpPath   string
		DownPath string
	}
	type serverGroup struct {
		Paths    []pathPort
		CertPath string
		KeyPath  string
	}
	grouped := make(map[string]*serverGroup)
	var serverNames []string
	for _, e := range entries {
		if e == nil || e.ServerName == "" || e.XHTTPPath == "" || e.InternalPort == 0 {
			continue
		}
		pp := pathPort{
			Path:     e.XHTTPPath,
			Port:     e.InternalPort,
			UpPath:   e.UpPath,
			DownPath: e.DownPath,
		}
		if g, ok := grouped[e.ServerName]; !ok {
			serverNames = append(serverNames, e.ServerName)
			grouped[e.ServerName] = &serverGroup{
				Paths:    []pathPort{pp},
				CertPath: e.CertPath,
				KeyPath:  e.KeyPath,
			}
		} else {
			g.Paths = append(g.Paths, pp)
			if g.CertPath == "" && e.CertPath != "" {
				g.CertPath = e.CertPath
			}
			if g.KeyPath == "" && e.KeyPath != "" {
				g.KeyPath = e.KeyPath
			}
		}
	}

	if len(serverNames) == 0 {
		return ""
	}

	var buf strings.Builder
	buf.WriteString("# yundu-https-xhttp-snippet.conf (auto-generated by YunDu nginxrender)\n")
	buf.WriteString("# XHTTP CDN 反代 vhost：proxy_pass 到 xray XHTTP inbound\n")
	buf.WriteString("# proxy_buffering off 以支持 XHTTP 流式传输（packet-up/stream-up/stream-down）\n\n")

	for _, sn := range serverNames {
		g := grouped[sn]
		buf.WriteString("server {\n")
		buf.WriteString(fmt.Sprintf("    listen %d ssl;\n", cfg.HTTPSListenPort))
		buf.WriteString(fmt.Sprintf("    server_name %s;\n\n", sn))

		effectiveCert := g.CertPath
		if effectiveCert == "" {
			effectiveCert = certPath
		}
		effectiveKey := g.KeyPath
		if effectiveKey == "" {
			effectiveKey = keyPath
		}
		if effectiveCert != "" && effectiveKey != "" {
			buf.WriteString(fmt.Sprintf("    ssl_certificate %s;\n", effectiveCert))
			buf.WriteString(fmt.Sprintf("    ssl_certificate_key %s;\n", effectiveKey))
			buf.WriteString("    ssl_protocols TLSv1.2 TLSv1.3;\n")
			buf.WriteString("    ssl_ciphers EECDH+CHACHA20:EECDH+AES128:EECDH+AES256:!MD5;\n")
			buf.WriteString("    ssl_prefer_server_ciphers on;\n")
			buf.WriteString("    ssl_session_cache shared:SSL:10m;\n")
			buf.WriteString("    ssl_session_timeout 10m;\n\n")
		}

		// Cloudflare 真实 IP
		buf.WriteString("    # Cloudflare 真实IP\n")
		buf.WriteString("    set_real_ip_from 103.21.244.0/22;\n")
		buf.WriteString("    set_real_ip_from 103.22.200.0/22;\n")
		buf.WriteString("    set_real_ip_from 103.31.4.0/22;\n")
		buf.WriteString("    set_real_ip_from 104.16.0.0/13;\n")
		buf.WriteString("    set_real_ip_from 104.24.0.0/14;\n")
		buf.WriteString("    set_real_ip_from 108.162.192.0/18;\n")
		buf.WriteString("    set_real_ip_from 131.0.72.0/22;\n")
		buf.WriteString("    set_real_ip_from 141.101.64.0/18;\n")
		buf.WriteString("    set_real_ip_from 162.158.0.0/15;\n")
		buf.WriteString("    set_real_ip_from 172.64.0.0/13;\n")
		buf.WriteString("    set_real_ip_from 173.245.48.0/20;\n")
		buf.WriteString("    set_real_ip_from 188.114.96.0/20;\n")
		buf.WriteString("    set_real_ip_from 190.93.240.0/22;\n")
		buf.WriteString("    set_real_ip_from 197.234.240.0/22;\n")
		buf.WriteString("    set_real_ip_from 198.41.128.0/17;\n")
		buf.WriteString("    real_ip_header CF-Connecting-IP;\n")
		buf.WriteString("    real_ip_recursive on;\n\n")

		for _, pp := range g.Paths {
			buf.WriteString(fmt.Sprintf("    # XHTTP -> 127.0.0.1:%d\n", pp.Port))
			buf.WriteString(fmt.Sprintf("    location %s {\n", pp.Path))
			buf.WriteString(fmt.Sprintf("        proxy_pass http://127.0.0.1:%d;\n", pp.Port))
			buf.WriteString("        proxy_http_version 1.1;\n")
			buf.WriteString("        proxy_set_header Host $host;\n")
			buf.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
			buf.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
			buf.WriteString("        proxy_buffering off;\n")
			buf.WriteString("        proxy_request_buffering off;\n")
			buf.WriteString("        proxy_read_timeout 300s;\n")
			buf.WriteString("        proxy_send_timeout 300s;\n")
			buf.WriteString("    }\n")
			// XHTTP split 模式：upPath（上行，proxy_buffering on 允许缓冲）
			if pp.UpPath != "" && pp.UpPath != pp.Path {
				buf.WriteString(fmt.Sprintf("    # XHTTP split upPath -> 127.0.0.1:%d\n", pp.Port))
				buf.WriteString(fmt.Sprintf("    location %s {\n", pp.UpPath))
				buf.WriteString(fmt.Sprintf("        proxy_pass http://127.0.0.1:%d;\n", pp.Port))
				buf.WriteString("        proxy_http_version 1.1;\n")
				buf.WriteString("        proxy_set_header Host $host;\n")
				buf.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
				buf.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
				buf.WriteString("        proxy_buffering on;\n")
				buf.WriteString("        proxy_request_buffering on;\n")
				buf.WriteString("        proxy_read_timeout 300s;\n")
				buf.WriteString("        proxy_send_timeout 300s;\n")
				buf.WriteString("    }\n")
			}
			// XHTTP split 模式：downPath（下行，proxy_buffering off 流式传输）
			if pp.DownPath != "" && pp.DownPath != pp.Path {
				buf.WriteString(fmt.Sprintf("    # XHTTP split downPath -> 127.0.0.1:%d\n", pp.Port))
				buf.WriteString(fmt.Sprintf("    location %s {\n", pp.DownPath))
				buf.WriteString(fmt.Sprintf("        proxy_pass http://127.0.0.1:%d;\n", pp.Port))
				buf.WriteString("        proxy_http_version 1.1;\n")
				buf.WriteString("        proxy_set_header Host $host;\n")
				buf.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
				buf.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
				buf.WriteString("        proxy_buffering off;\n")
				buf.WriteString("        proxy_request_buffering off;\n")
				buf.WriteString("        proxy_read_timeout 300s;\n")
				buf.WriteString("        proxy_send_timeout 300s;\n")
				buf.WriteString("    }\n")
			}
		}

		buf.WriteString("\n    # 默认返回 404\n    location / {\n        return 404;\n    }\n")
		buf.WriteString("}\n\n")
	}

	return buf.String()
}
