apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yundu.fullname" . }}-secrets
  labels:
    {{- include "yundu.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.nodeService.envSecrets.DB_PASSWORD | quote }}
  redis-password: {{ .Values.nodeService.envSecrets.REDIS_PASSWORD | quote }}
